/**
 * The leaves of Luna Shopper's category taxonomy, by root (backend plan 0173,
 * appendix A, which replaced the tree of plan 0166).
 *
 * **This is a copy, and it exists so that a typo fails a test.** The catalog's
 * reference seed owns the taxonomy and turns each slug into a row; this library
 * knows no ids and no database, so the only thing its resolver can answer is a
 * slug, and the only way to prove a slug it answers is real is to hold the list
 * here. `categories.spec.ts` asserts every slug the table names is one of these.
 *
 * A slug is an identity and never renamed after it ships, so the copy only ever
 * grows. A leaf added to the seed and not here is harmless: nothing here answers
 * it until the table is taught to.
 */
export const CATEGORY_LEAVES: Readonly<Record<string, readonly string[]>> = {
  fruits: [
    'bananas-and-plantains',
    'apples-and-pears',
    'oranges-tangerines-and-lemons',
    'melon-and-watermelon',
    'grapes',
    'tropical-fruits',
    'red-and-forest-fruits',
    'frozen-fruits',
    'other-fruits',
  ],
  vegetables: [
    'lettuce-and-leafy-greens',
    'tomatoes-peppers-and-cucumbers',
    'garlic-onions-and-leeks',
    'courgette-pumpkin-and-aubergine',
    'potatoes-and-carrots',
    'broccoli-cauliflower-and-green-beans',
    'mushrooms',
    'aromatic-herbs',
    'salads-and-prepared-vegetables',
    'frozen-and-steamed-vegetables',
    'vegetables-canned-vegetables',
  ],
  meats: [
    'chicken',
    'beef',
    'pork',
    'turkey',
    'rabbit',
    'hamburgers-ground-beef-and-meatballs',
    'breaded-and-prepared-foods',
    'cuts-and-cuts',
  ],
  'fish-and-seafood': [
    'fish-and-seafood-fresh',
    'fish-and-seafood-frozen',
    'breaded',
    'seafood-shrimp-and-squid',
    'smoked-and-salted',
    'surimi-and-prepared-products',
  ],
  charcuterie: [
    'cooked-ham',
    'turkey-and-chicken',
    'serrano-ham',
    'loin-and-chorizo',
    'fuet-and-salchichon',
    'chopped-and-mortadella',
    'sausages',
    'bacon',
    'pate-and-sobrasada',
  ],
  cheeses: [
    'cured',
    'semi-cured',
    'young-mild',
    'cheeses-fresh',
    'specialties',
    'blue-and-goat-cheese',
    'sliced',
    'shredded-grated',
    'spreadable-and-portions',
  ],
  'eggs-milk-and-butter': [
    'eggs',
    'milk',
    'lactose-free-and-fortified-milk',
    'plant-based-drinks-and-horchata',
    'infant-formula',
    'milkshakes',
    'condensed-and-evaporated-milk',
    'butter-and-margarine',
    'cream',
  ],
  bakery: [
    'freshly-baked-bread',
    'sliced-and-specialty-breads',
    'hamburger-and-hot-dog-buns',
    'wheat-tortillas-and-pita-bread',
    'gluten-free-bread',
    'breadcrumbs-toasted-bread-and-breadsticks',
    'oven',
    'doughs-and-pastries',
  ],
  'yoghurts-and-desserts': [
    'natural-and-skimmed-yogurts',
    'flavoured-and-fruit-yoghurts',
    'greek-yogurts',
    'liquid-yogurts',
    'bifidus-yoghurts-and-cholesterol',
    'kefir-and-plant-based-desserts',
    'protein-desserts-and-yogurts',
    'yogurts-and-children-s-desserts',
    'traditional-desserts',
    'custard-flan-and-rice-pudding',
    'gelatins-and-curds',
  ],
  'frozen-foods-and-ice-cream': [
    'pizzas-and-doughs',
    'croquettes-and-batters',
    'frozen-foods-and-ice-cream-fish-and-seafood',
    'vegetables-and-potatoes',
    'rice-and-pasta',
    'ice-creams-and-ice',
    'cakes-and-churros',
  ],
  'rice-pasta-and-pulses': [
    'rice',
    'rice-pasta-and-pulses-fideos',
    'macaroni-spaghetti-and-dried-pasta',
    'filled-and-sauced-pasta',
    'lasagna-and-cannelloni',
    'pasta-sauces',
    'rice-pasta-and-pulses-noodles',
    'gluten-free-pasta',
    'chickpeas-and-beans',
    'lentils',
    'quinoa-couscous-and-soy',
  ],
  'oils-sauces-and-spices': [
    'oils',
    'vinegars-and-dressings',
    'garlic-salt-and-pepper',
    'spices-and-herbs',
    'seasonings',
    'tomato-and-pasta-sauces',
    'special-and-spicy-sauces',
    'ketchup-mayonnaise-and-mustard',
  ],
  'canned-food-broths-and-creams': [
    'tuna-and-bonito',
    'mackerel-and-sardines',
    'mussels-cockles-and-fish',
    'pates',
    'canned-food-broths-and-creams-canned-vegetables',
    'canned-fruit',
    'creams-and-purees',
    'broths-and-soups',
  ],
  'coffee-cocoa-and-infusions': [
    'compatible-nespresso-capsules',
    'compatible-dolce-gusto-capsules',
    'other-compatible-capsules',
    'ground-coffee',
    'instant-coffee',
    'whole-bean-coffee',
    'cold-brew-coffee',
    'cocoa-and-hot-chocolate',
    'infusions',
    'tea',
  ],
  'pastries-cakes-and-sugar': [
    'sweet-baked-goods',
    'muffins-and-classic-pastries',
    'doughnuts-and-cakes',
    'pastries-cakes-and-sugar-cakes',
    'flours-and-yeasts',
    'dessert-mixes-and-decorations',
    'sugar-honey-and-sweeteners',
  ],
  'biscuits-cereals-and-jams': [
    'chocolate-and-filled-biscuits',
    'classic-and-digestive-biscuits',
    'savory-biscuits-and-crackers',
    'cereals',
    'whole-grain-cereals-and-muesli',
    'cereal-and-protein-bars',
    'biscuits-cereals-and-jams-cakes',
    'gluten-free-biscuits-cereals-and-pancakes',
    'jams',
  ],
  'chocolates-and-sweets': [
    'milk-chocolate',
    'dark-chocolate',
    'white-chocolate',
    'chocolates-and-bonbons',
    'cocoa-spreads-and-creams',
    'sweets',
    'chewing-gum-and-candies',
  ],
  'prepared-meals-and-pizzas': [
    'ready-to-eat-dishes',
    'tortillas-and-pies',
    'refrigerated-pizzas',
    'frozen-pizzas',
    'sandwiches-and-burgers',
    'traditional-food',
    'mexican-food',
    'asian-food',
    'salads-and-bowls',
    'gazpachos-and-salmorejos',
    'hummus-and-guacamole',
  ],
  'snacks-and-nuts': [
    'potato-chips',
    'savory-snacks',
    'vegetable-snacks',
    'nuts',
    'mixed-nuts',
    'dried-fruit',
    'olives',
    'pickles',
  ],
  'water-and-soft-drinks': [
    'water',
    'cola',
    'orange-lemon-and-lemon-lime',
    'tonic-sparkling-water-and-bitter',
    'iced-tea',
    'non-carbonated-soft-drinks',
    'isotonic-and-sports-drinks',
    'energy-drinks',
    'kombucha-and-vitamin-infused-waters',
    'water-and-soft-drink-packs',
  ],
  'juices-and-smoothies': [
    'freshly-squeezed-and-fresh',
    'orange',
    'lemonade',
    'peach-and-pineapple',
    'multifruit-and-other-flavors',
    'fruit-and-milk',
    'smoothies',
    'juice-packs',
  ],
  'beers-wines-and-spirits': [
    'beers',
    'premium-and-specialty-beers',
    'beers-with-lemon',
    'non-alcoholic-beers',
    'beer-packs',
    'summer-red-wine-and-sangria',
    'red-wine',
    'white-wine',
    'rose-wine',
    'cavas-and-cider',
    'gin-vodka-and-tequila',
    'ron-and-whisky',
    'vermouth-and-aperitifs',
    'creams-liqueurs-and-brandy',
  ],
  'cleaning-and-home': [
    'detergents',
    'fabric-softeners-and-laundry-care',
    'dishwasher',
    'toilet-paper-kitchen-paper-and-napkins',
    'garbage-bags-brooms-and-mops',
    'kitchen-cleaning-and-degreasing',
    'bathroom-and-toilet-cleaning',
    'cleaning-floors-windows-and-furniture',
    'bleach-and-disinfectants',
    'film-aluminum-and-preservation',
    'scouring-pads-cloths-and-gloves',
    'air-fresheners-refills-and-candles',
    'insecticides',
    'batteries-kitchenware-and-bags',
  ],
  'hygiene-and-body-care': [
    'shower-gel-and-sponges',
    'oral-hygiene',
    'deodorants',
    'shaving',
    'hair-removal',
    'sanitary-pads-and-feminine-hygiene',
    'body-and-hand-hydration',
    'hand-soap',
  ],
  'hair-and-perfumery': [
    'shampoo',
    'conditioners-and-masks',
    'foams-and-fixers',
    'dyes',
    'facial-care',
    'perfumes-and-colognes',
  ],
  'health-and-pharmacy': [
    'nutritional-supplements',
    'parapharmacy',
    'first-aid-kit',
    'sunscreen',
  ],
  children: [
    'milk-and-baby-food',
    'baby-foods-and-jars',
    'yogurt-and-desserts',
    'pots-and-snacks',
    'diapers-and-wipes',
    'hygiene-and-care',
    'children-juices-and-smoothies',
    'cookies-and-pastries',
    'sweets-and-chocolates',
  ],
  pets: [
    'wet-cat-food',
    'dry-cat-food',
    'cat-treats-and-care',
    'wet-dog-food',
    'dry-dog-food',
    'dog-treats-and-care',
  ],
  other: ['uncategorised'],
};

/** Every leaf slug, for the membership check. */
export const CATEGORY_LEAF_SLUGS: ReadonlySet<string> = new Set(
  Object.values(CATEGORY_LEAVES).flat()
);
