services:
  portfolio-app:
    image: node:22
    container_name: portfolio-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.nx
      - /app/.angular
    ports:
      - '4200-4300:4200-4300'
    command: >
      sh -c "npm ci && npx nx serve shell --host 0.0.0.0 --poll 1500"
