services:
  portfolio-app:
    image: node:22
    container_name: portfolio-dev-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.nx
      - /app/.angular
    ports:
      - '4200-4300:4200-4300'

    # Serve options are configured in the project.json file of the shell app
    # (/apps/shell/project.json).
    command: >
      sh -c "npm i && npx nx serve shell"
