version: '3.8'

services:
  angular-app:
    image: node:18
    container_name: angular-dev
    working_dir: /app
    volumes:
      - ./:/app           # Sync project code
      - /app/node_modules # Prevent overwriting node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && npx ng serve"