/**
 * Write `src/lib/categories.ts` from the research data of plan 0173 (plan
 * 0174, section 7).
 *
 *   npx nx run luna-shopper/dia:generate-categories
 *
 * `dia-map.json` maps every DIA id to one of our slugs: each copied root and
 * leaf to its own slug, and each node plan 0173 did not copy to the leaf its
 * only products belong under. A product is listed under a leaf and never under
 * a root, and it may be filed only on a leaf, so the table keeps the entries
 * whose slug is a leaf of the reference taxonomy and drops the root rows.
 *
 * It makes no request. Run it again when `dia-map.json` changes, and commit
 * the diff. `categories.spec.ts` fails when the two disagree.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CATEGORY_LEAF_SLUGS } from '../src/lib/category-leaves';

const ROOT = join(__dirname, '..', '..', '..', '..');
const DATA = join(
  ROOT,
  'apps/luna-shopper-backend/harvester/docs/research/dia/data'
);
const OUT = join(__dirname, '..', 'src', 'lib', 'categories.ts');

interface TreeNode {
  id: string;
  es: string;
}

function main(): void {
  const map = JSON.parse(
    readFileSync(join(DATA, 'dia-map.json'), 'utf8')
  ) as Record<string, string>;
  const names = new Map(
    (
      JSON.parse(
        readFileSync(join(DATA, 'category-tree.json'), 'utf8')
      ) as TreeNode[]
    )
      // A node the research saw only through a redirect has no name.
      .filter((node) => typeof node.es === 'string' && node.es !== '')
      .map((node) => [node.id, node.es])
  );

  const rows = Object.entries(map)
    .filter(([, slug]) => CATEGORY_LEAF_SLUGS.has(slug))
    .sort(([a], [b]) => a.length - b.length || a.localeCompare(b));

  const lines = [
    '// Generated by `nx run luna-shopper/dia:generate-categories` from',
    '// apps/luna-shopper-backend/harvester/docs/research/dia/data/dia-map.json',
    '// and category-tree.json (plan 0174, section 7). Never edit it by hand:',
    '// `categories.spec.ts` fails when this table and `dia-map.json` disagree.',
    '',
    '/** DIA leaf id to the slug of the leaf its products are filed under. */',
    'export const DIA_CATEGORY_SLUGS: Readonly<Record<string, string>> = {',
    ...rows.map(([id, slug]) => `  ${id}: '${slug}',`),
    '};',
    '',
    '/**',
    ' * The Spanish name of every id DIA served when the table was generated,',
    ' * mapped or not.',
    ' *',
    ' * Two questions are read from it. A walked leaf whose name differs from the',
    ' * one here was renamed, and DIA reuses an id with a new meaning. A walked',
    ' * leaf that is absent from here and from the table is new, and an operator',
    ' * has to map it. A leaf here and not in the table is unmapped on purpose:',
    ' * its products all sit in leaves that are mapped.',
    ' */',
    'export const DIA_CATEGORY_NAMES: Readonly<Record<string, string>> = {',
    ...[...names.entries()]
      .sort(([a], [b]) => a.length - b.length || a.localeCompare(b))
      .map(([id, name]) => `  ${id}: ${quote(name)},`),
    '};',
    '',
  ];
  writeFileSync(OUT, lines.join('\n'), 'utf8');
  process.stdout.write(
    `wrote ${rows.length} of ${Object.keys(map).length} ids\n`
  );
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

main();
