<#
.SYNOPSIS
  Configure this checkout (a git worktree, usually) to run the Luna Shopper
  backend on an isolated "slot", so several worktrees can run the compose stack
  and `nx serve` the four services at once without colliding on ports, container
  names, or databases. PowerShell twin of luna-slot.sh.

.EXAMPLE
  ./k8s/e2e/luna-shopper-backend/luna-slot.ps1 1
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot `
    -f k8s/e2e/luna-shopper-backend/compose.yml up -d
  npx nx serve luna-shopper-gateway

.DESCRIPTION
  A slot is an integer N. Every host port is default + N*100, the compose project
  (its containers, network, and named volumes) is "luna-slot<N>", and the four
  services listen on 300{0..3}+N*100. Slot 0 keeps the original ports and the
  "luna-shopper" project name, so a lone worktree needs no slot. (Re)writes, all
  git ignored: .env.slot (compose), apps/luna-shopper/.env.luna-shopper, each
  service .env, and the dev JWT keypair (generated once if absent). Idempotent.
#>
[CmdletBinding()]
param([Parameter(Mandatory)][int]$Slot)

$ErrorActionPreference = 'Stop'
if ($Slot -lt 0) { throw 'slot must be a non-negative integer' }

$here = $PSScriptRoot
$root = (Resolve-Path (Join-Path $here '..\..\..')).Path
$off = $Slot * 100

$authDb   = 5432 + $off
$coreDb   = 5433 + $off
$nats     = 4222 + $off
$natsMon  = 8222 + $off
$smtp     = 1025 + $off
$mailUi   = 8025 + $off
$gateway  = 3000 + $off
$realtime = 3001 + $off
$auth     = 3002 + $off
$core     = 3003 + $off
$project  = if ($Slot -eq 0) { 'luna-shopper' } else { "luna-slot$Slot" }

$secrets = Join-Path $root 'apps/luna-shopper/secrets'
New-Item -ItemType Directory -Force -Path $secrets | Out-Null
if (-not (Test-Path (Join-Path $secrets 'jwt.key'))) {
  Write-Host 'generating a throwaway dev JWT keypair in apps/luna-shopper/secrets ...'
  & openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out (Join-Path $secrets 'jwt.key')
  & openssl pkey -in (Join-Path $secrets 'jwt.key') -pubout -out (Join-Path $secrets 'jwt.pub')
}

function Write-EnvFile($path, $content) {
  Set-Content -Path $path -Value $content -Encoding utf8 -NoNewline
}

Write-EnvFile (Join-Path $here '.env.slot') @"
# Generated by luna-slot.ps1 for slot $Slot. Git ignored.
COMPOSE_PROJECT_NAME=$project
LUNA_AUTH_DB_PORT=$authDb
LUNA_CORE_DB_PORT=$coreDb
LUNA_NATS_PORT=$nats
LUNA_NATS_MONITOR_PORT=$natsMon
LUNA_SMTP_PORT=$smtp
LUNA_MAILPIT_UI_PORT=$mailUi
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper/.env.luna-shopper') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
NATS_URL=nats://localhost:$nats
LOG_LEVEL=debug
CORS_ORIGINS=http://localhost:4200
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper/gateway/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
PORT=$gateway
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper/realtime/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
PORT=$realtime
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper/auth/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
AUTH_DB_URL=postgres://luna_auth:luna_auth@localhost:$authDb/luna_auth
AUTH_JWT_PRIVATE_KEY_FILE=./apps/luna-shopper/secrets/jwt.key
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
AUTH_JWT_KID=dev-1
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL=30d
SMTP_HOST=localhost
SMTP_PORT=$smtp
SMTP_USER=
SMTP_PASS=
MAIL_FROM=Luna Shopper <no-reply@luna.localhost>
MAIL_VERIFY_BASE_URL=http://localhost:4200/verify-email
GOOGLE_CLIENT_ID=your-dev-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-dev-client-secret
GOOGLE_CALLBACK_URL=http://localhost:$gateway/auth/google/callback
PORT=$auth
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper/core/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
CORE_DB_URL=postgres://luna_core:luna_core@localhost:$coreDb/luna_core
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
PORT=$core
"@

Write-Host ""
Write-Host "Configured this worktree for Luna Shopper slot $Slot."
Write-Host "  compose project : $project"
Write-Host "  auth-db localhost:$authDb   core-db localhost:$coreDb"
Write-Host "  nats localhost:$nats (mon $natsMon)   smtp $smtp   mailpit http://localhost:$mailUi"
Write-Host "  gateway $gateway   realtime $realtime   auth $auth   core $core"
Write-Host ""
Write-Host "  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot ``"
Write-Host "    -f k8s/e2e/luna-shopper-backend/compose.yml up -d"
