<#
.SYNOPSIS
  Configure this checkout (a git worktree, usually) to run the Luna Shopper
  backend on an isolated "slot", so several worktrees can run the compose stack
  and `nx serve` the four services at once without colliding on ports, container
  names, or databases. PowerShell twin of luna-slot.sh.

.EXAMPLE
  ./k8s/e2e/luna-shopper-backend/luna-slot.ps1 1
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot `
    -f k8s/e2e/luna-shopper-backend/compose.yml up -d
  npx nx serve luna-shopper-backend-gateway

.DESCRIPTION
  A slot is an integer N. Every host port is default + N*100, the compose project
  (its containers, network, and named volumes) is "luna-slot<N>", and the four
  services listen on 300{0..3}+N*100. Slot 0 keeps the original ports and the
  "luna-shopper-backend" project name, so a lone worktree needs no slot. (Re)writes, all
  git ignored: .env.slot (compose), apps/luna-shopper-backend/.env.luna-shopper-backend, each
  service .env, and the dev JWT keypair (generated once if absent). Idempotent.
#>
[CmdletBinding()]
param([Parameter(Mandatory)][int]$Slot)

$ErrorActionPreference = 'Stop'
if ($Slot -lt 0) { throw 'slot must be a non-negative integer' }

$here = $PSScriptRoot
$root = (Resolve-Path (Join-Path $here '..\..\..')).Path
$off = $Slot * 100

$authDb    = 5432 + $off
$coreDb    = 5433 + $off
$catalogDb = 5434 + $off
$nats      = 4222 + $off
$natsMon   = 8222 + $off
$smtp      = 1025 + $off
$mailUi    = 8025 + $off
$gateway   = 3000 + $off
$realtime  = 3001 + $off
$auth      = 3002 + $off
$core      = 3003 + $off
$catalog   = 3004 + $off
# Observability stack (plan 0016, section 9). Opt in via the `observability`
# compose profile; the ports are reserved per slot either way so two worktrees
# can each run their own collector without colliding.
$otlpGrpc   = 4317 + $off
$otlpHttp   = 4318 + $off
$jaegerUi   = 16686 + $off
$prometheus = 9090 + $off
$grafana    = 3010 + $off
$project  = if ($Slot -eq 0) { 'luna-shopper-backend' } else { "luna-slot$Slot" }

$secrets = Join-Path $root 'apps/luna-shopper-backend/secrets'
New-Item -ItemType Directory -Force -Path $secrets | Out-Null
if (-not (Test-Path (Join-Path $secrets 'jwt.key'))) {
  Write-Host 'generating a throwaway dev JWT keypair in apps/luna-shopper-backend/secrets ...'
  & openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out (Join-Path $secrets 'jwt.key')
  & openssl pkey -in (Join-Path $secrets 'jwt.key') -pubout -out (Join-Path $secrets 'jwt.pub')
}

function Write-EnvFile($path, $content) {
  Set-Content -Path $path -Value $content -Encoding utf8 -NoNewline
}

Write-EnvFile (Join-Path $here '.env.slot') @"
# Generated by luna-slot.ps1 for slot $Slot. Git ignored.
COMPOSE_PROJECT_NAME=$project
LUNA_AUTH_DB_PORT=$authDb
LUNA_CORE_DB_PORT=$coreDb
LUNA_CATALOG_DB_PORT=$catalogDb
LUNA_NATS_PORT=$nats
LUNA_NATS_MONITOR_PORT=$natsMon
LUNA_SMTP_PORT=$smtp
LUNA_MAILPIT_UI_PORT=$mailUi
LUNA_OTLP_GRPC_PORT=$otlpGrpc
LUNA_OTLP_HTTP_PORT=$otlpHttp
LUNA_JAEGER_UI_PORT=$jaegerUi
LUNA_PROMETHEUS_PORT=$prometheus
LUNA_GRAFANA_PORT=$grafana
# The collector scrapes the services on the host, so it needs their ports too.
LUNA_GATEWAY_PORT=$gateway
LUNA_REALTIME_PORT=$realtime
LUNA_AUTH_PORT=$auth
LUNA_CORE_PORT=$core
LUNA_CATALOG_PORT=$catalog
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper-backend/.env.luna-shopper-backend') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
NATS_URL=nats://localhost:$nats
LOG_LEVEL=debug
CORS_ORIGINS=http://localhost:4200
# Telemetry deliberately does NOT live here; see the note in each service's .env.
"@

# Telemetry (plan 0016), written into every service's own .env rather than the
# shared file above. That placement is load bearing, not tidiness: the SDK starts
# from process.env before Nest exists (section 4.1), and only @nestjs/config ever
# reads .env.luna-shopper-backend, whose custom name nothing else knows. Nx does
# load {projectRoot}/.env into the environment of that project's tasks, so a
# variable put here reaches the SDK under `nx serve`; the same variable in the
# shared file would be read too late and silently ignored.
function Get-TelemetryEnv($service) {
  return @"

# --- Telemetry (plan 0016) ---------------------------------------------------
# Read by the OpenTelemetry SDK before Nest boots, so it has to be in this file
# rather than the shared one (Nx loads a project's own .env; nothing loads the
# shared file into the environment). Pointed at this slot's collector, which
# exists only while the ``observability`` compose profile is up. With the profile
# down the batch processor drops spans and warns, requests are unaffected, so
# leaving this on costs nothing; set OTEL_ENABLED=false to silence it.
OTEL_SERVICE_NAME=luna-shopper-backend-$service
OTEL_ENABLED=true
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:$otlpHttp
OTEL_TRACES_SAMPLER_ARG=1.0
DEPLOYMENT_ENVIRONMENT=development
METRICS_ENABLED=true
"@
}

Write-EnvFile (Join-Path $root 'apps/luna-shopper-backend/gateway/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PORT=$gateway
# Google sign in runs at the gateway (plan 0023), so the OAuth variables live
# here as well as in auth's env. The credentials are placeholders: with a client
# id set the routes are live, which is what lets the state mint and the refusal
# of a bad state be driven locally without a real consent screen.
GOOGLE_CLIENT_ID=your-dev-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-dev-client-secret
GOOGLE_CALLBACK_URL=http://localhost:$gateway/v1/auth/google/callback
# Where the callback sends the browser. {locale} is substituted with the locale
# the flow started in; the app sits under a path that follows the locale segment.
APP_BASE_URL=http://localhost:4200/{locale}/velista
$(Get-TelemetryEnv 'gateway')
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper-backend/realtime/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PORT=$realtime
$(Get-TelemetryEnv 'realtime')
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper-backend/auth/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
AUTH_DB_URL=postgres://luna_auth:luna_auth@localhost:$authDb/luna_auth
AUTH_JWT_PRIVATE_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.key
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
AUTH_JWT_KID=dev-1
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL=30d
SMTP_HOST=localhost
SMTP_PORT=$smtp
SMTP_USER=
SMTP_PASS=
MAIL_FROM=Luna Shopper <no-reply@luna.localhost>
MAIL_VERIFY_BASE_URL=http://localhost:4200/verify-email
MAIL_RESET_BASE_URL=http://localhost:4200/reset-password
GOOGLE_CLIENT_ID=your-dev-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-dev-client-secret
GOOGLE_CALLBACK_URL=http://localhost:$gateway/auth/google/callback
PORT=$auth
$(Get-TelemetryEnv 'auth')
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper-backend/core/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
CORE_DB_URL=postgres://luna_core:luna_core@localhost:$coreDb/luna_core
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PORT=$core
$(Get-TelemetryEnv 'core')
"@

Write-EnvFile (Join-Path $root 'apps/luna-shopper-backend/catalog/.env') @"
# Generated by luna-slot.ps1 (slot $Slot). Git ignored.
CATALOG_DB_URL=postgres://luna_catalog:luna_catalog@localhost:$catalogDb/luna_catalog
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PLATFORM_ADMIN_USER_IDS=
PORT=$catalog
$(Get-TelemetryEnv 'catalog')
"@

Write-Host ""
Write-Host "Configured this worktree for Luna Shopper slot $Slot."
Write-Host "  compose project : $project"
Write-Host "  auth-db localhost:$authDb   core-db localhost:$coreDb   catalog-db localhost:$catalogDb"
Write-Host "  nats localhost:$nats (mon $natsMon)   smtp $smtp   mailpit http://localhost:$mailUi"
Write-Host "  gateway $gateway   realtime $realtime   auth $auth   core $core   catalog $catalog"
Write-Host "  otlp http/grpc $otlpHttp / $otlpGrpc   jaeger http://localhost:$jaegerUi"
Write-Host "  prometheus http://localhost:$prometheus   grafana http://localhost:$grafana"
Write-Host ""
Write-Host "  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot ``"
Write-Host "    -f k8s/e2e/luna-shopper-backend/compose.yml up -d"
Write-Host ""
Write-Host "Add the traces and metrics view (plan 0016), which is opt in:"
Write-Host "  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot ``"
Write-Host "    --profile observability ``"
Write-Host "    -f k8s/e2e/luna-shopper-backend/compose.yml up -d"
