#!/usr/bin/env bash
#
# luna-slot.sh — configure this checkout (a git worktree, usually) to run the
# Luna Shopper backend on an isolated "slot" so several worktrees can bring up
# the compose stack and `nx serve` the four services at the same time without
# fighting over ports, container names, or databases.
#
# Usage, from the workspace root of the worktree you want to configure:
#
#   bash k8s/e2e/luna-shopper-backend/luna-slot.sh <slot>    # slot = 0 | 1 | 2 | ...
#   docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \
#     -f k8s/e2e/luna-shopper-backend/compose.yml up -d
#   npx nx serve luna-shopper-backend-gateway     # etc. — reads the .env files written below
#
# What a slot is: an integer N. Every host port is its default + N*100, the
# compose project (and therefore its containers, network, and named volumes) is
# "luna-slot<N>", and the four services listen on 300{0..3}+N*100. Slot 0 is the
# original single stack (default ports, project "luna-shopper-backend" is kept for N=0
# so the plain `docker compose ... up` workflow still matches), so a lone
# worktree needs no slot at all.
#
# This script (re)writes, all git ignored, so it is safe per worktree:
#   - k8s/e2e/luna-shopper-backend/.env.slot   (compose: project name + host ports)
#   - apps/luna-shopper-backend/.env.luna-shopper-backend       (shared service vars)
#   - apps/luna-shopper-backend/{gateway,realtime,auth,core}/.env
#   - apps/luna-shopper-backend/secrets/jwt.{key,pub}   (generated once if absent)
#
# It is idempotent: run it again with the same slot to refresh, or a different
# slot to move this worktree.
set -euo pipefail

slot="${1:-}"
if ! [[ "$slot" =~ ^[0-9]+$ ]]; then
  echo "usage: luna-slot.sh <slot>   (a non-negative integer, e.g. 0, 1, 2)" >&2
  exit 2
fi

# Resolve the workspace root from this script's location (…/k8s/e2e/luna-shopper-backend).
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../../.." && pwd)"
cd "$root"

off=$(( slot * 100 ))

# Host ports (compose). Kept > 100 apart per service so slots never overlap.
AUTH_DB_PORT=$(( 5432 + off ))
CORE_DB_PORT=$(( 5433 + off ))
CATALOG_DB_PORT=$(( 5434 + off ))
NATS_PORT=$(( 4222 + off ))
NATS_MON_PORT=$(( 8222 + off ))
REDIS_PORT=$(( 6379 + off ))
SMTP_PORT=$(( 1025 + off ))
MAILPIT_UI_PORT=$(( 8025 + off ))

# Observability stack (plan 0016, section 9). Opt in via the `observability`
# compose profile; these ports are reserved per slot either way so two worktrees
# can each run their own collector without colliding.
OTLP_GRPC_PORT=$(( 4317 + off ))
OTLP_HTTP_PORT=$(( 4318 + off ))
JAEGER_UI_PORT=$(( 16686 + off ))
PROMETHEUS_PORT=$(( 9090 + off ))
GRAFANA_PORT=$(( 3010 + off ))

# Service listen ports.
GATEWAY_PORT=$(( 3000 + off ))
REALTIME_PORT=$(( 3001 + off ))
AUTH_PORT=$(( 3002 + off ))
CORE_PORT=$(( 3003 + off ))
CATALOG_PORT=$(( 3004 + off ))

if [[ "$slot" == "0" ]]; then
  project="luna-shopper-backend"   # keep the historic name so the no-slot workflow matches
else
  project="luna-slot${slot}"
fi

secrets="$root/apps/luna-shopper-backend/secrets"
mkdir -p "$secrets"
if [[ ! -f "$secrets/jwt.key" ]]; then
  echo "generating a throwaway dev JWT keypair in apps/luna-shopper-backend/secrets ..."
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$secrets/jwt.key" 2>/dev/null
  openssl pkey -in "$secrets/jwt.key" -pubout -out "$secrets/jwt.pub" 2>/dev/null
fi

# --- compose env-file --------------------------------------------------------
cat > "$here/.env.slot" <<EOF
# Generated by luna-slot.sh for slot ${slot}. Git ignored. Pass to compose with
#   docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot -f <compose> up -d
COMPOSE_PROJECT_NAME=${project}
LUNA_AUTH_DB_PORT=${AUTH_DB_PORT}
LUNA_CORE_DB_PORT=${CORE_DB_PORT}
LUNA_CATALOG_DB_PORT=${CATALOG_DB_PORT}
LUNA_NATS_PORT=${NATS_PORT}
LUNA_NATS_MONITOR_PORT=${NATS_MON_PORT}
LUNA_REDIS_PORT=${REDIS_PORT}
LUNA_SMTP_PORT=${SMTP_PORT}
LUNA_MAILPIT_UI_PORT=${MAILPIT_UI_PORT}
LUNA_OTLP_GRPC_PORT=${OTLP_GRPC_PORT}
LUNA_OTLP_HTTP_PORT=${OTLP_HTTP_PORT}
LUNA_JAEGER_UI_PORT=${JAEGER_UI_PORT}
LUNA_PROMETHEUS_PORT=${PROMETHEUS_PORT}
LUNA_GRAFANA_PORT=${GRAFANA_PORT}
# The collector scrapes the services on the host, so it needs their ports too.
LUNA_GATEWAY_PORT=${GATEWAY_PORT}
LUNA_REALTIME_PORT=${REALTIME_PORT}
LUNA_AUTH_PORT=${AUTH_PORT}
LUNA_CORE_PORT=${CORE_PORT}
LUNA_CATALOG_PORT=${CATALOG_PORT}
EOF

# --- shared service env ------------------------------------------------------
cat > "$root/apps/luna-shopper-backend/.env.luna-shopper-backend" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
NATS_URL=nats://localhost:${NATS_PORT}
REDIS_URL=redis://localhost:${REDIS_PORT}
LOG_LEVEL=debug
CORS_ORIGINS=http://localhost:4200
# Telemetry deliberately does NOT live here; see the note in each service's .env.
EOF

# Telemetry (plan 0016), written into every service's own .env rather than the
# shared file above. That placement is load bearing, not tidiness: the SDK starts
# from `process.env` before Nest exists (section 4.1), and only @nestjs/config
# ever reads `.env.luna-shopper-backend`, whose custom name nothing else knows.
# Nx *does* load `{projectRoot}/.env` into the environment of that project's
# tasks, so a variable put here reaches the SDK under `nx serve`; the same
# variable in the shared file would be read too late and silently ignored.
telemetry_env() {
  cat <<EOF

# --- Telemetry (plan 0016) ---------------------------------------------------
# Read by the OpenTelemetry SDK before Nest boots, so it has to be in this file
# rather than the shared one (Nx loads a project's own .env; nothing loads the
# shared file into the environment). Pointed at this slot's collector, which
# exists only while the \`observability\` compose profile is up. With the profile
# down the batch processor drops spans and warns, requests are unaffected, so
# leaving this on costs nothing; set OTEL_ENABLED=false to silence it.
OTEL_SERVICE_NAME=luna-shopper-backend-$1
OTEL_ENABLED=true
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:${OTLP_HTTP_PORT}
OTEL_TRACES_SAMPLER_ARG=1.0
DEPLOYMENT_ENVIRONMENT=development
METRICS_ENABLED=true
EOF
}

# --- per service env ---------------------------------------------------------
cat > "$root/apps/luna-shopper-backend/gateway/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PORT=${GATEWAY_PORT}
# Google sign in runs at the gateway (plan 0023), so the OAuth variables live
# here as well as in auth's env. The credentials are placeholders: with a client
# id set the routes are live, which is what lets the state mint and the refusal
# of a bad state be driven locally without a real consent screen.
GOOGLE_CLIENT_ID=your-dev-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-dev-client-secret
GOOGLE_CALLBACK_URL=http://localhost:${GATEWAY_PORT}/v1/auth/google/callback
# Where the callback sends the browser. {locale} is substituted with the locale
# the flow started in; the app sits under a path that follows the locale segment.
APP_BASE_URL=http://localhost:4200/{locale}/velista
EOF
telemetry_env gateway >> "$root/apps/luna-shopper-backend/gateway/.env"

cat > "$root/apps/luna-shopper-backend/realtime/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PORT=${REALTIME_PORT}
EOF
telemetry_env realtime >> "$root/apps/luna-shopper-backend/realtime/.env"

cat > "$root/apps/luna-shopper-backend/auth/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
AUTH_DB_URL=postgres://luna_auth:luna_auth@localhost:${AUTH_DB_PORT}/luna_auth
AUTH_JWT_PRIVATE_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.key
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
AUTH_JWT_KID=dev-1
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL=30d
SMTP_HOST=localhost
SMTP_PORT=${SMTP_PORT}
SMTP_USER=
SMTP_PASS=
MAIL_FROM=Luna Shopper <no-reply@luna.localhost>
MAIL_VERIFY_BASE_URL=http://localhost:4200/verify-email
MAIL_RESET_BASE_URL=http://localhost:4200/reset-password
GOOGLE_CLIENT_ID=your-dev-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-dev-client-secret
GOOGLE_CALLBACK_URL=http://localhost:${GATEWAY_PORT}/auth/google/callback
PORT=${AUTH_PORT}
EOF
telemetry_env auth >> "$root/apps/luna-shopper-backend/auth/.env"

cat > "$root/apps/luna-shopper-backend/core/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
CORE_DB_URL=postgres://luna_core:luna_core@localhost:${CORE_DB_PORT}/luna_core
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PORT=${CORE_PORT}
EOF
telemetry_env core >> "$root/apps/luna-shopper-backend/core/.env"

cat > "$root/apps/luna-shopper-backend/catalog/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
CATALOG_DB_URL=postgres://luna_catalog:luna_catalog@localhost:${CATALOG_DB_PORT}/luna_catalog
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper-backend/secrets/jwt.pub
PLATFORM_ADMIN_USER_IDS=
PORT=${CATALOG_PORT}
EOF
telemetry_env catalog >> "$root/apps/luna-shopper-backend/catalog/.env"

cat <<EOF

Configured this worktree for Luna Shopper slot ${slot}.
  compose project : ${project}
  auth-db         : localhost:${AUTH_DB_PORT}      core-db  : localhost:${CORE_DB_PORT}
  catalog-db      : localhost:${CATALOG_DB_PORT}
  nats            : localhost:${NATS_PORT} (mon ${NATS_MON_PORT})
  redis           : localhost:${REDIS_PORT}
  smtp / mailpit  : localhost:${SMTP_PORT} / http://localhost:${MAILPIT_UI_PORT}
  gateway ${GATEWAY_PORT}   realtime ${REALTIME_PORT}   auth ${AUTH_PORT}   core ${CORE_PORT}   catalog ${CATALOG_PORT}
  otlp http/grpc  : localhost:${OTLP_HTTP_PORT} / ${OTLP_GRPC_PORT}
  jaeger / graf   : http://localhost:${JAEGER_UI_PORT} / http://localhost:${GRAFANA_PORT}
  prometheus      : http://localhost:${PROMETHEUS_PORT}

Bring up the isolated stack:
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \\
    -f k8s/e2e/luna-shopper-backend/compose.yml up -d
Add the traces and metrics view (plan 0016), which is opt in:
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \\
    --profile observability \\
    -f k8s/e2e/luna-shopper-backend/compose.yml up -d
Tear it down (removes just this slot's containers + volumes):
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \\
    -f k8s/e2e/luna-shopper-backend/compose.yml down -v
EOF
