#!/usr/bin/env bash
#
# luna-slot.sh — configure this checkout (a git worktree, usually) to run the
# Luna Shopper backend on an isolated "slot" so several worktrees can bring up
# the compose stack and `nx serve` the four services at the same time without
# fighting over ports, container names, or databases.
#
# Usage, from the workspace root of the worktree you want to configure:
#
#   bash k8s/e2e/luna-shopper-backend/luna-slot.sh <slot>    # slot = 0 | 1 | 2 | ...
#   docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \
#     -f k8s/e2e/luna-shopper-backend/compose.yml up -d
#   npx nx serve luna-shopper-gateway     # etc. — reads the .env files written below
#
# What a slot is: an integer N. Every host port is its default + N*100, the
# compose project (and therefore its containers, network, and named volumes) is
# "luna-slot<N>", and the four services listen on 300{0..3}+N*100. Slot 0 is the
# original single stack (default ports, project "luna-shopper" is kept for N=0
# so the plain `docker compose ... up` workflow still matches), so a lone
# worktree needs no slot at all.
#
# This script (re)writes, all git ignored, so it is safe per worktree:
#   - k8s/e2e/luna-shopper-backend/.env.slot   (compose: project name + host ports)
#   - apps/luna-shopper/.env.luna-shopper       (shared service vars)
#   - apps/luna-shopper/{gateway,realtime,auth,core}/.env
#   - apps/luna-shopper/secrets/jwt.{key,pub}   (generated once if absent)
#
# It is idempotent: run it again with the same slot to refresh, or a different
# slot to move this worktree.
set -euo pipefail

slot="${1:-}"
if ! [[ "$slot" =~ ^[0-9]+$ ]]; then
  echo "usage: luna-slot.sh <slot>   (a non-negative integer, e.g. 0, 1, 2)" >&2
  exit 2
fi

# Resolve the workspace root from this script's location (…/k8s/e2e/luna-shopper-backend).
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../../.." && pwd)"
cd "$root"

off=$(( slot * 100 ))

# Host ports (compose). Kept > 100 apart per service so slots never overlap.
AUTH_DB_PORT=$(( 5432 + off ))
CORE_DB_PORT=$(( 5433 + off ))
NATS_PORT=$(( 4222 + off ))
NATS_MON_PORT=$(( 8222 + off ))
SMTP_PORT=$(( 1025 + off ))
MAILPIT_UI_PORT=$(( 8025 + off ))

# Service listen ports.
GATEWAY_PORT=$(( 3000 + off ))
REALTIME_PORT=$(( 3001 + off ))
AUTH_PORT=$(( 3002 + off ))
CORE_PORT=$(( 3003 + off ))

if [[ "$slot" == "0" ]]; then
  project="luna-shopper"   # keep the historic name so the no-slot workflow matches
else
  project="luna-slot${slot}"
fi

secrets="$root/apps/luna-shopper/secrets"
mkdir -p "$secrets"
if [[ ! -f "$secrets/jwt.key" ]]; then
  echo "generating a throwaway dev JWT keypair in apps/luna-shopper/secrets ..."
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$secrets/jwt.key" 2>/dev/null
  openssl pkey -in "$secrets/jwt.key" -pubout -out "$secrets/jwt.pub" 2>/dev/null
fi

# --- compose env-file --------------------------------------------------------
cat > "$here/.env.slot" <<EOF
# Generated by luna-slot.sh for slot ${slot}. Git ignored. Pass to compose with
#   docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot -f <compose> up -d
COMPOSE_PROJECT_NAME=${project}
LUNA_AUTH_DB_PORT=${AUTH_DB_PORT}
LUNA_CORE_DB_PORT=${CORE_DB_PORT}
LUNA_NATS_PORT=${NATS_PORT}
LUNA_NATS_MONITOR_PORT=${NATS_MON_PORT}
LUNA_SMTP_PORT=${SMTP_PORT}
LUNA_MAILPIT_UI_PORT=${MAILPIT_UI_PORT}
EOF

# --- shared service env ------------------------------------------------------
cat > "$root/apps/luna-shopper/.env.luna-shopper" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
NATS_URL=nats://localhost:${NATS_PORT}
LOG_LEVEL=debug
CORS_ORIGINS=http://localhost:4200
EOF

# --- per service env ---------------------------------------------------------
cat > "$root/apps/luna-shopper/gateway/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
PORT=${GATEWAY_PORT}
EOF

cat > "$root/apps/luna-shopper/realtime/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
PORT=${REALTIME_PORT}
EOF

cat > "$root/apps/luna-shopper/auth/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
AUTH_DB_URL=postgres://luna_auth:luna_auth@localhost:${AUTH_DB_PORT}/luna_auth
AUTH_JWT_PRIVATE_KEY_FILE=./apps/luna-shopper/secrets/jwt.key
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
AUTH_JWT_KID=dev-1
ACCESS_TOKEN_TTL=15m
REFRESH_TOKEN_TTL=30d
SMTP_HOST=localhost
SMTP_PORT=${SMTP_PORT}
SMTP_USER=
SMTP_PASS=
MAIL_FROM=Luna Shopper <no-reply@luna.localhost>
MAIL_VERIFY_BASE_URL=http://localhost:4200/verify-email
GOOGLE_CLIENT_ID=your-dev-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-dev-client-secret
GOOGLE_CALLBACK_URL=http://localhost:${GATEWAY_PORT}/auth/google/callback
PORT=${AUTH_PORT}
EOF

cat > "$root/apps/luna-shopper/core/.env" <<EOF
# Generated by luna-slot.sh (slot ${slot}). Git ignored.
CORE_DB_URL=postgres://luna_core:luna_core@localhost:${CORE_DB_PORT}/luna_core
AUTH_JWT_PUBLIC_KEY_FILE=./apps/luna-shopper/secrets/jwt.pub
PORT=${CORE_PORT}
EOF

cat <<EOF

Configured this worktree for Luna Shopper slot ${slot}.
  compose project : ${project}
  auth-db         : localhost:${AUTH_DB_PORT}      core-db  : localhost:${CORE_DB_PORT}
  nats            : localhost:${NATS_PORT} (mon ${NATS_MON_PORT})
  smtp / mailpit  : localhost:${SMTP_PORT} / http://localhost:${MAILPIT_UI_PORT}
  gateway ${GATEWAY_PORT}   realtime ${REALTIME_PORT}   auth ${AUTH_PORT}   core ${CORE_PORT}

Bring up the isolated stack:
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \\
    -f k8s/e2e/luna-shopper-backend/compose.yml up -d
Tear it down (removes just this slot's containers + volumes):
  docker compose --env-file k8s/e2e/luna-shopper-backend/.env.slot \\
    -f k8s/e2e/luna-shopper-backend/compose.yml down -v
EOF
