ARG BUILDER_TAG=latest
ARG TARGET_REGISTRY
ARG NX_APP

# Use the builder image to build the microfrontend app
# TO-DO: set the builder image tag, right now it uses latest always which means
# that dev tag is never used at all which is confusing
# Also it might not make much sense to use another image as base if we are going to
# build an app and the image might not have the code updated
FROM ${TARGET_REGISTRY}nx-portfolio/builder:${BUILDER_TAG} AS builder
ENV NODE_ENV=test
ARG NX_APP
RUN npx nx test ${NX_APP}
