import { ToothTreatment, ToothZones, TreatmentStatus, TreatmentType } from "@portfolio/odontogram/models";

export const TREATMENTS: readonly ToothTreatment[] = [
  {
    id: "1",
    odontogram: "1",
    teeth: ["11", "12", "21"],
    groupedTeeth: true,
    status: TreatmentStatus.COMPLETED,
    zones: [ToothZones.ROOT],
    type: TreatmentType.EXTRACTION,
    additionalInformation: "Extraction treatment for teeth 11, 12, and 21",
    updatedAt: new Date("2025-01-02"),
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "2",
    odontogram: "1",
    teeth: ["37"],
    groupedTeeth: true,
    status: TreatmentStatus.PENDING,
    zones: [ToothZones.BOTTOM],
    type: TreatmentType.STANDARD,
    additionalInformation: "Standard treatment for teeth 37",
    updatedAt: new Date("2025-02-02"),
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "3",
    odontogram: "2",
    teeth: ["11", "12", "21"],
    groupedTeeth: false,
    status: TreatmentStatus.PENDING,
    zones: [ToothZones.ROOT],
    type: TreatmentType.IMPLANT,
    additionalInformation: "Implant treatment for teeth 11, 12, and 21",
    updatedAt: new Date("2025-03-02"),
    createdAt: new Date("2025-03-01"),
  },
  {
    id: "4",
    odontogram: "3",
    teeth: ["28"],
    groupedTeeth: false,
    status: TreatmentStatus.COMPLETED,
    zones: [ToothZones.LATERAL],
    type: TreatmentType.STANDARD,
    additionalInformation: "Filling for tooth 28",
    updatedAt: new Date("2025-04-02"),
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "5",
    odontogram: "3",
    teeth: ["27"],
    groupedTeeth: false,
    status: TreatmentStatus.COMPLETED,
    zones: [ToothZones.LATERAL],
    type: TreatmentType.STANDARD,
    additionalInformation: "Filling for tooth 27",
    updatedAt: new Date("2025-04-02"),
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "6",
    odontogram: "3",
    teeth: ["37"],
    groupedTeeth: false,
    status: TreatmentStatus.COMPLETED,
    zones: [ToothZones.LATERAL],
    type: TreatmentType.STANDARD,
    additionalInformation: "Filling for tooth 37",
    updatedAt: new Date("2025-04-02"),
    createdAt: new Date("2025-04-01"),
  }
];
