import { ItemCategory, UnitOfMeasure } from '@portfolio/luna-shopper/contracts';
import type { AuthoredItem } from './types';

const { KILOGRAM, LITER, UNIT } = UnitOfMeasure;
const {
  BAKERY,
  BEVERAGES,
  DAIRY,
  FROZEN,
  HOUSEHOLD,
  MEAT,
  OTHER,
  PANTRY,
  PERSONAL_CARE,
  PRODUCE,
  SNACKS,
} = ItemCategory;

/**
 * El Jamón, 16 products (plan 0067, section 4.2).
 *
 * This is the store whose receipt names most need the exercise: `GARBANZA
 * FRASC` and `BOCADIT.CODAN` are not names anybody would search for.
 *
 * Three of its receipt lines are **not here**, and that is the deliberate part.
 * `CARNICERIA`, `CHARCUTERIA` and `PANADERIA` are the counter that rang the sale
 * up, not a product: what was bought is recorded nowhere on the ticket. A
 * catalog is a list of things you can buy again, and "whatever the butcher
 * handed over on the 28th" is not one of them. The receipt total still knows the
 * money was spent; the catalog does not have to invent a product to hold it.
 */
export const EL_JAMON_ITEMS: AuthoredItem[] = [
  {
    slug: 'judias-findus',
    name: { en: 'Frozen Green Beans', es: 'Judías verdes congeladas' },
    group: 'frozen-green-beans',
    category: FROZEN,
    defaultUnit: KILOGRAM,
    brand: 'Findus',
    receipt: 'JUDIAS FINDUS',
    price: 1.99,
    observedAt: '2026-08-28',
  },
  {
    slug: 'garbanzos-frasco',
    name: { en: 'Chickpeas in a Jar', es: 'Garbanzos en frasco' },
    group: 'chickpeas',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    receipt: 'GARBANZA FRASC',
    price: 1.15,
    observedAt: '2026-08-28',
  },
  {
    slug: 'aquadeus-50cl',
    name: { en: 'Still Water 50 cl', es: 'Agua mineral 50 cl' },
    group: 'still-water',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Aquadeus',
    receipt: 'AQUADEUS 50CL',
    price: 0.31,
    observedAt: '2026-08-28',
  },
  {
    slug: 'queso-mezcla-capicua',
    name: { en: 'Mixed Milk Cheese', es: 'Queso mezcla Capicúa' },
    group: 'semi-cured-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Capicúa',
    receipt: 'MEZCLA CAPICUA',
    price: 14.25,
    observedAt: '2026-08-28',
  },
  {
    slug: 'coletero',
    name: { en: 'Hair Tie', es: 'Coletero' },
    group: 'hair-tie',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    receipt: 'COLETERO',
    price: 1.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'espetec-eliges',
    name: { en: 'Fuet', es: 'Fuet espetec' },
    group: 'fuet',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Eliges',
    receipt: 'ESPETEC ELIGES',
    price: 2.1,
    observedAt: '2026-07-25',
  },
  {
    slug: 'pate-125g',
    name: { en: 'Pâté 125 g', es: 'Paté 125 g' },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    receipt: 'PATE 125G',
    price: 1.32,
    observedAt: '2026-07-25',
  },
  {
    slug: 'bocaditos-codan',
    name: { en: 'Filled Mini Buns', es: 'Bocaditos rellenos' },
    group: 'filled-buns',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Codan',
    receipt: 'BOCADIT.CODAN',
    price: 1.19,
    observedAt: '2026-07-25',
  },
  {
    slug: 'bolsa-el-jamon',
    name: { en: 'Carrier Bag', es: 'Bolsa de la compra' },
    group: 'carrier-bag',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    receipt: 'BOLSA EL JAMON',
    price: 0.15,
    observedAt: '2026-07-25',
  },
  {
    slug: 'bocatin-180g',
    name: { en: 'Sandwich Roll 180 g', es: 'Bocatín 180 g' },
    group: 'bread-rolls',
    category: BAKERY,
    defaultUnit: UNIT,
    receipt: 'BOCATIN 180G',
    price: 0.55,
    observedAt: '2026-07-25',
  },
  {
    slug: 'pepito-nata',
    name: { en: 'Cream Filled Bun', es: 'Pepito de nata' },
    group: 'filled-buns',
    category: BAKERY,
    defaultUnit: UNIT,
    receipt: 'PEPITO NATA',
    price: 1.95,
    observedAt: '2026-07-25',
  },
  {
    slug: 'pepito-crema',
    name: { en: 'Custard Filled Bun', es: 'Pepito de crema' },
    group: 'filled-buns',
    category: BAKERY,
    defaultUnit: UNIT,
    receipt: 'PEPITO CREMA',
    price: 1.95,
    observedAt: '2026-07-25',
  },
  {
    slug: 'queso-el-jamon',
    name: { en: 'Semi Cured Cheese Wedge', es: 'Cuña de queso semicurado' },
    group: 'semi-cured-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'El Jamón',
    receipt: 'QUESO EL JAMON',
    price: 3.0,
    observedAt: '2026-07-17',
  },
  {
    slug: 'iberitos-250g',
    name: { en: 'Iberian Pâté 250 g', es: 'Paté ibérico 250 g' },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Iberitos',
    receipt: 'IBERITOS 250G',
    price: 2.29,
    observedAt: '2026-07-17',
  },
  {
    slug: 'mini-biscotes',
    name: { en: 'Mini Melba Toast', es: 'Mini biscotes' },
    group: 'melba-toast',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    receipt: 'MINI BISCOTES',
    price: 0.76,
    observedAt: '2026-07-17',
  },
  {
    slug: 'fontvella-15l',
    name: { en: 'Still Water 1.5 L', es: 'Agua mineral 1,5 L' },
    group: 'still-water',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Font Vella',
    receipt: 'FONTVELLA 1.5L',
    price: 0.76,
    observedAt: '2026-07-17',
  },
];

/**
 * SuperCash, 107 products (plan 0067, section 4.3).
 *
 * The till prints a readable name already, so normalizing here is mostly
 * pulling the brand out of the description and dropping the pack size, which is
 * what makes a name a name rather than a shelf label: "Atún claro aceite de
 * oliva ALTEZA" becomes Tinned Tuna in Olive Oil, brand Alteza. The eight
 * `Laca de uñas E.LLORCA nº NNN` rows stay eight items, because they are eight
 * different colours and one group already says they are the same purchase.
 *
 * `Fruteria CASH2` is left out for the same reason as El Jamón's three counter
 * lines: it names the counter, not what came off it.
 */
export const SUPERCASH_ITEMS: AuthoredItem[] = [
  {
    slug: 'rotuladores-pizarra-3',
    name: {
      en: 'Whiteboard Markers, Pack of 3',
      es: 'Rotuladores de pizarra, pack de 3',
    },
    group: 'whiteboard-markers',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Bismark',
    receipt: '3 rotuladores pizarra BISMARK 4 fine',
    price: 1.29,
    observedAt: '2026-08-21',
  },
  {
    slug: 'rotulador-pizarra-negro',
    name: { en: 'Black Whiteboard Marker', es: 'Rotulador de pizarra negro' },
    group: 'whiteboard-markers',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Bismark',
    receipt: 'Rotulador pizarra BISMARK negro',
    price: 0.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'agua-cabreiroa',
    name: {
      en: 'Still Water, Sports Cap',
      es: 'Agua mineral con tapón deportivo',
    },
    group: 'still-water',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Cabreiroá',
    receipt: 'Agua mineral natural CABREIROA tapón',
    price: 0.52,
    observedAt: '2026-08-28',
  },
  {
    slug: 'agua-font-natura',
    name: { en: 'Still Water 8 L', es: 'Agua mineral 8 L' },
    group: 'still-water',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Font Natura',
    receipt: 'Agua mineral natural FONT NATURA 8',
    price: 0.94,
    observedAt: '2026-08-28',
  },
  {
    slug: 'ambientador-air-wick',
    name: { en: 'Decorative Air Freshener', es: 'Ambientador decorativo' },
    group: 'air-freshener',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Air Wick',
    receipt: 'Ambientador AIR WICK DECOSPHERE',
    price: 3.85,
    observedAt: '2026-08-28',
  },
  {
    slug: 'ambientador-campero',
    name: {
      en: 'Concentrated Air Freshener Spray',
      es: 'Ambientador concentrado en spray',
    },
    group: 'air-freshener',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Campero',
    receipt: 'Ambientador concentrado CAMPERO spray',
    price: 1.37,
    observedAt: '2026-08-28',
  },
  {
    slug: 'ambientador-atmosphere',
    name: { en: 'Air Freshener Beads', es: 'Ambientador en perlas' },
    group: 'air-freshener',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Atmosphere',
    receipt: 'Ambientador perlas ATMOSPHERE',
    price: 1.35,
    observedAt: '2026-08-28',
  },
  {
    slug: 'atun-claro-oliva',
    name: {
      en: 'Tinned Tuna in Olive Oil',
      es: 'Atún claro en aceite de oliva',
    },
    group: 'tinned-tuna',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Atún claro aceite de oliva ALTEZA',
    price: 2.29,
    observedAt: '2026-08-28',
  },
  {
    slug: 'azucar-moreno',
    name: { en: 'Unrefined Brown Sugar', es: 'Azúcar moreno sin refinar' },
    group: 'brown-sugar',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Azúcar moreno sin refinar ALTEZA',
    price: 1.79,
    observedAt: '2026-08-21',
  },
  {
    slug: 'bacon-ahumado',
    name: { en: 'Smoked Bacon', es: 'Bacon ahumado' },
    group: 'bacon',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Bacon ahumado natural ALTEZA',
    price: 7.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'bizcocho-codan',
    name: { en: 'Baked Sponge Cakes', es: 'Bizcocho horneado' },
    group: 'sponge-cake',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Codan',
    receipt: 'Bizcocho horneado CODAN Robin 4 ud',
    price: 1.35,
    observedAt: '2026-08-28',
  },
  {
    slug: 'bocaditos-limon',
    name: { en: 'Lemon Biscuits', es: 'Bocaditos de limón' },
    group: 'plain-biscuits',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Cuétara',
    receipt: 'Bocaditos de limón CUÉTARA 150 g',
    price: 1.14,
    observedAt: '2026-08-28',
  },
  {
    slug: 'bombon-menorquina',
    name: { en: 'Nougat Ice Cream Bars', es: 'Bombones helados de turrón' },
    group: 'ice-cream-bars',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'La Menorquina',
    receipt: 'Bombón LA MENORQUINA turrón 3x100 ml',
    price: 3.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'bote-salsa',
    name: { en: 'Round Sauce Tub', es: 'Bote redondo para salsa' },
    group: 'food-storage-tubs',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Great Plastic',
    receipt: 'Bote redondo salsa GREAT PLASTIC',
    price: 0.78,
    observedAt: '2026-08-21',
  },
  {
    slug: 'budin-cerdo',
    name: { en: 'Pork Terrine', es: 'Budín de cerdo' },
    group: 'pork-terrine',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Prolongo',
    receipt: 'Budín de cerdo PROLONGO',
    price: 7.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'bulgaros-cacao',
    name: { en: 'Cocoa Cereal Balls', es: 'Búlgaros al cacao' },
    group: 'cocoa-cereal-balls',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Búlgaros al cacao ALTEZA 5 ud 175 g',
    price: 1.19,
    observedAt: '2026-08-21',
  },
  {
    slug: 'cabeza-jabali',
    name: { en: 'Head Cheese', es: 'Cabeza de jabalí' },
    group: 'head-cheese',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Picken',
    receipt: 'Cabeza de jabalí Suprema PICKEN',
    price: 13.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'capsulas-gimoka',
    name: { en: 'Decaf Coffee Capsules', es: 'Cápsulas de café descafeinado' },
    group: 'coffee-capsules',
    category: PANTRY,
    defaultUnit: UNIT,
    brand: 'Gimoka',
    receipt: 'Café cápsulas GIMOKA descafeinado',
    price: 2.85,
    observedAt: '2026-08-14',
  },
  {
    slug: 'capsulas-tassimo',
    name: { en: 'Tassimo Coffee Capsules', es: 'Cápsulas de café Tassimo' },
    group: 'coffee-capsules',
    category: PANTRY,
    defaultUnit: UNIT,
    brand: 'Marcilla',
    receipt: 'Café cápsulas Marcilla TASSIMO',
    price: 5.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'caramelos-miel',
    name: { en: 'Honey Sweets', es: 'Caramelos de miel' },
    group: 'boiled-sweets',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Respiral',
    receipt: 'Caramelos de miel RESPIRAL 150 g',
    price: 1.76,
    observedAt: '2026-08-28',
  },
  {
    slug: 'carpeta-anillas',
    name: { en: 'A4 Four Ring Binder', es: 'Carpeta A4 de 4 anillas' },
    group: 'ring-binder',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Bismark',
    receipt: 'Carpeta cartón A4 4 anillas BISMARK',
    price: 2.59,
    observedAt: '2026-08-21',
  },
  {
    slug: 'champinon-bandeja',
    name: { en: 'Whole Mushrooms', es: 'Champiñón entero en bandeja' },
    group: 'mushrooms',
    category: PRODUCE,
    defaultUnit: KILOGRAM,
    receipt: 'Champiñón bandeja 300 g',
    price: 1.49,
    observedAt: '2026-08-14',
  },
  {
    slug: 'champinon-laminado',
    name: { en: 'Sliced Mushrooms', es: 'Champiñón laminado' },
    group: 'mushrooms',
    category: PRODUCE,
    defaultUnit: KILOGRAM,
    receipt: 'Champiñón laminado 250 g',
    price: 1.69,
    observedAt: '2026-08-21',
  },
  {
    slug: 'champu-pantene',
    name: { en: 'Purifying Shampoo', es: 'Champú purificante' },
    group: 'shampoo',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Pantene',
    receipt: 'Champú purificante PANTENE 300 ml',
    price: 3.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'chocolate-milka-caramelo',
    name: {
      en: 'Caramel Milk Chocolate',
      es: 'Chocolate con leche y caramelo',
    },
    group: 'milk-chocolate',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Milka',
    receipt: 'Chocolate MILKA Caramelo 100 g',
    price: 1.86,
    observedAt: '2026-08-21',
  },
  {
    slug: 'chopped-pork',
    name: { en: 'Chopped Pork', es: 'Chopped pork' },
    group: 'chopped-pork',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Campofrío',
    receipt: 'Chopped pork CAMPOFRIO',
    price: 7.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'chorizo-pollo-alpico',
    name: { en: 'Chicken Chorizo', es: 'Chorizo de pollo' },
    group: 'chorizo',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Alpico',
    receipt: 'Chorizo 100% de pollo ALPICO vela',
    price: 15.45,
    observedAt: '2026-08-21',
    perKilo: true,
  },
  {
    slug: 'chorizo-pamplona',
    name: { en: 'Pamplona Chorizo', es: 'Chorizo extra de Pamplona' },
    group: 'chorizo',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Chorizo extra Pamplona ALTEZA',
    price: 6.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'cocktail-el-valle',
    name: { en: 'Snack Cocktail Mix', es: 'Cóctel de aperitivo' },
    group: 'nut-mix',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'El Valle',
    receipt: 'Cocktail supreme EL VALLE 85 g',
    price: 0.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'comida-gato-tandy',
    name: {
      en: 'Wet Cat Food for Neutered Cats',
      es: 'Comida húmeda para gato esterilizado',
    },
    group: 'wet-cat-food',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Tandy',
    receipt: 'Comida gato TANDY esterilizado 1.5',
    price: 1.89,
    observedAt: '2026-08-28',
  },
  {
    slug: 'comida-perro-buey',
    name: {
      en: 'Wet Dog Food with Beef',
      es: 'Comida húmeda para perro de buey',
    },
    group: 'wet-dog-food',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Tandy',
    receipt: 'Comida perro TANDY buey tarrina 300',
    price: 0.72,
    observedAt: '2026-08-14',
  },
  {
    slug: 'comida-perro-pollo',
    name: {
      en: 'Wet Dog Food with Chicken',
      es: 'Comida húmeda para perro de pollo',
    },
    group: 'wet-dog-food',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Tandy',
    receipt: 'Comida perro TANDY pollo tarrina 300',
    price: 0.82,
    observedAt: '2026-08-28',
  },
  {
    slug: 'cono-helado-nata',
    name: { en: 'Cream Ice Cream Cones', es: 'Conos de helado de nata' },
    group: 'ice-cream-cones',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Alteza',
    receipt: 'Cono helado ALTEZA nata 6x120 ml',
    price: 2.09,
    observedAt: '2026-08-21',
  },
  {
    slug: 'cono-helado-vainilla',
    name: {
      en: 'Vanilla and Caramel Ice Cream Cones',
      es: 'Conos de helado de vainilla y caramelo',
    },
    group: 'ice-cream-cones',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Alteza',
    receipt: 'Cono helado ALTEZA vainilla y caramelo',
    price: 1.89,
    observedAt: '2026-08-14',
  },
  {
    slug: 'miniconos-surtidos',
    name: { en: 'Assorted Mini Ice Cream Cones', es: 'Miniconos surtidos' },
    group: 'ice-cream-cones',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Alteza',
    receipt: 'Miniconos surtidos ALTEZA 12x30 ml',
    price: 2.5,
    observedAt: '2026-08-14',
  },
  {
    slug: 'coquitos-cartujano',
    name: { en: 'Coconut Macaroons', es: 'Coquitos' },
    group: 'traditional-pastries',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'El Cartujano',
    receipt: 'Coquitos EL CARTUJANO 115 g',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'cortadillos-cidra',
    name: { en: 'Pumpkin Jam Pastries', es: 'Cortadillos de cidra' },
    group: 'traditional-pastries',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'San Martín',
    receipt: 'Cortadillos de cidra SAN MARTÍN',
    price: 1.76,
    observedAt: '2026-08-28',
  },
  {
    slug: 'crema-jamon-york',
    name: { en: 'Ham and Cheese Spread', es: 'Crema de jamón york y queso' },
    group: 'cheese-spread',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Iberitos',
    receipt: 'Crema de jamón york queso IBERITOS',
    price: 2.69,
    observedAt: '2026-08-14',
  },
  {
    slug: 'croissants-rellenos',
    name: {
      en: 'Cocoa Cream Croissants',
      es: 'Croissants rellenos de crema de cacao',
    },
    group: 'filled-croissants',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Croissants rellenos ALTEZA crema cacao',
    price: 1.68,
    observedAt: '2026-08-21',
  },
  {
    slug: 'desodorante-calzado',
    name: { en: 'Shoe Deodorant', es: 'Desodorante para calzado' },
    group: 'shoe-deodorant',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Palc',
    receipt: 'Desodorante calzado PALC 125 ml',
    price: 1.69,
    observedAt: '2026-08-21',
  },
  {
    slug: 'desodorante-crowe',
    name: { en: 'Invisible Deodorant', es: 'Desodorante invisible' },
    group: 'deodorant',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Crowe',
    receipt: 'Desodorante invisible CROWE Man 200',
    price: 1.55,
    observedAt: '2026-08-21',
  },
  {
    slug: 'fiambre-paleta',
    name: { en: 'Cooked Shoulder Ham', es: 'Fiambre de paleta' },
    group: 'cooked-shoulder-ham',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'ElPozo',
    receipt: 'Fiambre paleta Sándwich ELPOZO',
    price: 5.75,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'fideos-cabellin',
    name: { en: 'Fine Soup Noodles', es: 'Fideos cabellín' },
    group: 'noodles',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Fideos cabellín ALTEZA 500 g',
    price: 0.69,
    observedAt: '2026-08-28',
  },
  {
    slug: 'flan-huevo',
    name: { en: 'Egg Crème Caramel', es: 'Flan de huevo' },
    group: 'creme-caramel',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Flan de huevo ALTEZA al baño María',
    price: 1.59,
    observedAt: '2026-08-21',
  },
  {
    slug: 'flan-vainilla',
    name: { en: 'Vanilla Crème Caramel', es: 'Flan de vainilla' },
    group: 'creme-caramel',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Flan de vainilla ALTEZA 4x100 g',
    price: 0.73,
    observedAt: '2026-08-21',
  },
  {
    slug: 'fregona-azmark',
    name: { en: 'Microfibre Mop Head', es: 'Fregona de microfibra' },
    group: 'mop-head',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Azmark',
    receipt: 'Fregona microfibra AZMARK doble paño',
    price: 1.87,
    observedAt: '2026-08-14',
  },
  {
    slug: 'friegasuelos-agerul',
    name: { en: 'Insecticide Floor Cleaner', es: 'Friegasuelos insecticida' },
    group: 'insecticide-floor-cleaner',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Agerul',
    receipt: 'Friegasuelos insecticida AGERUL',
    price: 2.64,
    observedAt: '2026-08-14',
  },
  {
    slug: 'frutas-leche-caribe',
    name: {
      en: 'Caribbean Fruit and Milk Drink',
      es: 'Bebida de frutas con leche caribe',
    },
    group: 'fruit-and-milk-drink',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Alteza',
    receipt: 'Frutas+leche ALTEZA caribe 6x200 ml',
    price: 1.16,
    observedAt: '2026-08-28',
  },
  {
    slug: 'funda-multitaladro',
    name: { en: 'Clear Punched Pockets', es: 'Fundas multitaladro cristal' },
    group: 'punched-pockets',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Bismark',
    receipt: 'Funda multitaladro t/f BISMARK cristal',
    price: 0.66,
    observedAt: '2026-08-21',
  },
  {
    slug: 'galletas-simpsons',
    name: { en: 'Mini Chocolate Biscuits', es: 'Galletas mini de chocolate' },
    group: 'chocolate-biscuits',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Arluy',
    receipt: 'Galletas mini Simpsons ARLUY chocolate',
    price: 2.74,
    observedAt: '2026-08-28',
  },
  {
    slug: 'galletas-rellenas-chocolate',
    name: {
      en: 'Chocolate Filled Biscuits',
      es: 'Galletas rellenas de chocolate',
    },
    group: 'chocolate-biscuits',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Galletas rellenas chocolate ALTEZA',
    price: 1.29,
    observedAt: '2026-08-21',
  },
  {
    slug: 'galletas-integrales-mondat',
    name: { en: 'Wholemeal Biscuits', es: 'Galletas integrales' },
    group: 'plain-biscuits',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Mondat',
    receipt: 'Integrales MONDAT 8 ud 360 g',
    price: 0.99,
    observedAt: '2026-08-21',
  },
  {
    slug: 'gel-bano-tulipan',
    name: { en: 'Strawberry Shower Gel', es: 'Gel de baño de fresa' },
    group: 'shower-gel',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Tulipán Negro',
    receipt: 'Gel de baño TULIPÁN NEGRO fresa',
    price: 1.82,
    observedAt: '2026-08-14',
  },
  {
    slug: 'gominolas-surtidas',
    name: { en: 'Assorted Jelly Sweets', es: 'Gominolas surtidas' },
    group: 'jelly-sweets',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Gominolas mega surtidas ALTEZA',
    price: 0.69,
    observedAt: '2026-08-21',
  },
  {
    slug: 'harina-trigo',
    name: { en: 'Plain Wheat Flour', es: 'Harina de trigo' },
    group: 'plain-flour',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Harina de trigo ALTEZA 1 kg',
    price: 0.68,
    observedAt: '2026-08-14',
  },
  {
    slug: 'harina-freir',
    name: { en: 'Frying Flour', es: 'Harina para freír' },
    group: 'frying-flour',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Panaeras Sevillanas',
    receipt: 'Harina para freír PANAERAS SEVILLANAS',
    price: 1.42,
    observedAt: '2026-08-28',
  },
  {
    slug: 'huevos-clase-l',
    name: { en: 'Large Eggs', es: 'Huevos clase L' },
    group: 'eggs',
    category: DAIRY,
    defaultUnit: UNIT,
    brand: 'Alteza',
    receipt: 'Huevos clase L 63/73 g ALTEZA',
    price: 4.39,
    observedAt: '2026-08-28',
  },
  {
    slug: 'ice-coffee-capuccino',
    name: { en: 'Iced Cappuccino', es: 'Café frío capuccino' },
    group: 'iced-coffee',
    category: PANTRY,
    defaultUnit: LITER,
    brand: 'Alteza',
    receipt: 'Ice coffee ALTEZA capuccino 250 ml',
    price: 0.74,
    observedAt: '2026-08-28',
  },
  {
    slug: 'jamon-serrano',
    name: { en: 'Boneless Serrano Ham', es: 'Jamón serrano deshuesado' },
    group: 'serrano-ham',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Juan del Valle',
    receipt: 'Jamón serrano deshuesado JUAN DEL VALLE',
    price: 24.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'ketchup-alteza',
    name: { en: 'Ketchup', es: 'Ketchup' },
    group: 'ketchup',
    category: PANTRY,
    defaultUnit: LITER,
    brand: 'Alteza',
    receipt: 'Ketchup ALTEZA 560 g',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-304',
    name: { en: 'Nail Polish nº 304', es: 'Laca de uñas nº 304' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 304 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-309',
    name: { en: 'Nail Polish nº 309', es: 'Laca de uñas nº 309' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 309 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-311',
    name: { en: 'Nail Polish nº 311', es: 'Laca de uñas nº 311' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 311 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-315',
    name: { en: 'Nail Polish nº 315', es: 'Laca de uñas nº 315' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 315 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-331',
    name: { en: 'Nail Polish nº 331', es: 'Laca de uñas nº 331' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 331 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-387',
    name: { en: 'Nail Polish nº 387', es: 'Laca de uñas nº 387' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 387 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-389',
    name: { en: 'Nail Polish nº 389', es: 'Laca de uñas nº 389' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 389 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'laca-unas-396',
    name: { en: 'Nail Polish nº 396', es: 'Laca de uñas nº 396' },
    group: 'nail-polish',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'E. Llorca',
    receipt: 'Laca de uñas E.LLORCA nº 396 8 ml',
    price: 0.95,
    observedAt: '2026-08-28',
  },
  {
    slug: 'lejia-gel-ace',
    name: { en: 'Thick Bleach Gel', es: 'Lejía en gel' },
    group: 'bleach',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'ACE',
    receipt: 'Lejía gel ACE protección no salpica',
    price: 1.99,
    observedAt: '2026-08-21',
  },
  {
    slug: 'mascarilla-elvive',
    name: {
      en: 'Hyaluronic Hair Mask',
      es: 'Mascarilla capilar de hialurónico',
    },
    group: 'hair-mask',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Elvive',
    receipt: 'Mascarilla capilar ELVIVE Hidra Hialurónico',
    price: 4.1,
    observedAt: '2026-08-21',
  },
  {
    slug: 'mayonesa-musa',
    name: { en: 'Mayonnaise', es: 'Mayonesa' },
    group: 'mayonnaise',
    category: PANTRY,
    defaultUnit: LITER,
    brand: 'Musa',
    receipt: 'Mayonesa MUSA 225 ml',
    price: 1.49,
    observedAt: '2026-08-28',
  },
  {
    slug: 'mortadela-siciliana',
    name: { en: 'Sicilian Mortadella', es: 'Mortadela siciliana' },
    group: 'mortadella',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'ElPozo',
    receipt: 'Mortadela siciliana ELPOZO',
    price: 5.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'cintas-adhesivas',
    name: { en: 'Adhesive Tape, Pack of 2', es: 'Cinta adhesiva, pack de 2' },
    group: 'adhesive-tape',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Bismark',
    receipt: 'Pack 2 cintas adhesivas BISMARK 20',
    price: 0.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'pan-molde-integral',
    name: { en: 'Sliced Wholemeal Bread', es: 'Pan de molde 100% integral' },
    group: 'sliced-wholemeal-bread',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Pan de molde 100% integral ALTEZA',
    price: 0.78,
    observedAt: '2026-08-21',
  },
  {
    slug: 'pan-sandwich-cereales',
    name: { en: 'Ten Grain Sandwich Bread', es: 'Pan de molde de 10 cereales' },
    group: 'sliced-wholemeal-bread',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Pan sandwich styles ALTEZA 10 cereales',
    price: 1.12,
    observedAt: '2026-08-21',
  },
  {
    slug: 'patatas-abuelo-antonio',
    name: { en: 'Crisps', es: 'Patatas fritas de bolsa' },
    group: 'crisps',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'El Abuelo Antonio',
    receipt: 'Patatas fritas EL ABUELO ANTONIO',
    price: 2.1,
    observedAt: '2026-08-28',
  },
  {
    slug: 'pate-campana',
    name: { en: 'Country Pâté', es: 'Paté de campaña' },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Paté de campaña ALTEZA 160 g',
    price: 0.92,
    observedAt: '2026-08-28',
  },
  {
    slug: 'pate-morcilla-pinones',
    name: {
      en: 'Black Pudding and Pine Nut Pâté',
      es: 'Paté de morcilla y piñones',
    },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Cazorla',
    receipt: 'Paté de morcilla y piñones CAZORLA',
    price: 1.38,
    observedAt: '2026-08-21',
  },
  {
    slug: 'pate-pollo-tarradellas',
    name: { en: 'Chicken Pâté', es: 'Paté de pollo' },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Casa Tarradellas',
    receipt: 'Paté de pollo CASA TARRADELLAS 125',
    price: 1.08,
    observedAt: '2026-08-14',
  },
  {
    slug: 'pate-iberico-iberitos',
    name: { en: 'Iberian Pâté', es: 'Paté ibérico' },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Iberitos',
    receipt: 'Paté ibérico IBERITOS 250 g',
    price: 2.38,
    observedAt: '2026-08-14',
  },
  {
    slug: 'pate-pamplonica',
    name: { en: 'Pâté, Pack of 3', es: 'Paté, pack de 3' },
    group: 'pate',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Pamplonica',
    receipt: 'Paté PAMPLONICA 3x80 g',
    price: 1.34,
    observedAt: '2026-08-28',
  },
  {
    slug: 'pechuga-pavo-braseada',
    name: { en: 'Braised Turkey Breast', es: 'Pechuga de pavo braseada' },
    group: 'sliced-turkey-breast',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'ElPozo',
    receipt: 'Pechuga de pavo braseada ELPOZO',
    price: 13.9,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'perlas-lenor',
    name: { en: 'Laundry Scent Beads', es: 'Perlas de perfume para la ropa' },
    group: 'laundry-scent-beads',
    category: HOUSEHOLD,
    defaultUnit: KILOGRAM,
    brand: 'Lenor',
    receipt: 'Perlas de perfume LENOR UNSTOPPABLE',
    price: 8.3,
    observedAt: '2026-08-21',
  },
  {
    slug: 'picos-artesanos',
    name: { en: 'Garlic Breadsticks', es: 'Picos artesanos con ajo' },
    group: 'breadsticks',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Hnos. Guerra',
    receipt: 'Picos artesanos HNOS.GUERRA con ajo',
    price: 2.12,
    observedAt: '2026-08-21',
  },
  {
    slug: 'queso-oveja-arquespal',
    name: { en: 'Aged Sheep Cheese', es: 'Queso de oveja viejo' },
    group: 'cured-sheep-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Arquespal',
    receipt: 'Queso de oveja viejo ARQUESPAL Reserva',
    price: 16.75,
    observedAt: '2026-08-28',
    perKilo: true,
  },
  {
    slug: 'queso-fresco-la-chacha',
    name: { en: 'Traditional Fresh Cheese', es: 'Queso fresco tradicional' },
    group: 'fresh-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'La Chacha',
    receipt: 'Queso fresco tradicional LA CHACHA SEBAS',
    price: 11.45,
    observedAt: '2026-07-24',
    perKilo: true,
  },
  {
    slug: 'queso-mezcla-garcia-baquero',
    name: { en: 'Semi Cured Mixed Cheese', es: 'Queso mezcla semicurado' },
    group: 'semi-cured-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'García Baquero',
    receipt: 'Queso mezcla semicurado GARCÍA BAQUERO',
    price: 16.9,
    observedAt: '2026-08-14',
    perKilo: true,
  },
  {
    slug: 'queso-rallado-hilo',
    name: { en: 'Grated Cheese', es: 'Queso rallado en hilo' },
    group: 'grated-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Queso rallado fundido hilo ALTEZA',
    price: 1.09,
    observedAt: '2026-08-21',
  },
  {
    slug: 'quitapelos-nobleza',
    name: {
      en: 'Pet Hair Remover for Laundry',
      es: 'Quitapelos de mascotas para la colada',
    },
    group: 'pet-hair-remover',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Nobleza',
    receipt: 'Quita pelos mascotas NOBLEZA colada',
    price: 1.21,
    observedAt: '2026-08-21',
  },
  {
    slug: 'quitamanchas-plus-max',
    name: { en: 'Oxi Active Stain Remover', es: 'Quitamanchas oxi activo' },
    group: 'stain-remover',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Plus Max',
    receipt: 'Quitamanchas oxi activo PLUS MAX',
    price: 1.75,
    observedAt: '2026-08-21',
  },
  {
    slug: 'recambio-a4-pacsa',
    name: { en: 'A4 Squared Binder Paper', es: 'Recambio A4 cuadriculado' },
    group: 'binder-paper',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Pacsa',
    receipt: 'Recambio A-4 4 anillas PACSA cuadro',
    price: 2.48,
    observedAt: '2026-08-21',
  },
  {
    slug: 'recambio-antimosquitos',
    name: { en: 'Mosquito Repellent Refill', es: 'Recambio antimosquitos' },
    group: 'mosquito-repellent-refill',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Selex',
    receipt: 'Recambio antimosquitos SELEX 33 ml',
    price: 1.6,
    observedAt: '2026-08-21',
  },
  {
    slug: 'revuelto-sagacor',
    name: { en: 'Scrambled Egg Mix', es: 'Revuelto preparado' },
    group: 'scrambled-egg-mix',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Sagacor',
    receipt: 'Revuelto pasarratos SAGACOR 500 g',
    price: 2.3,
    observedAt: '2026-08-28',
  },
  {
    slug: 'rollitos-takis',
    name: { en: 'Spicy Corn Rolls', es: 'Rollitos de maíz picantes' },
    group: 'corn-snacks',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Takis',
    receipt: 'Rollitos de maíz blue heat TAKIS',
    price: 2.15,
    observedAt: '2026-08-21',
  },
  {
    slug: 'sal-yodada',
    name: { en: 'Fine Iodised Salt', es: 'Sal yodada fina' },
    group: 'table-salt',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Chalupa',
    receipt: 'Sal yodada fina CHALUPA 1 kg',
    price: 0.34,
    observedAt: '2026-08-21',
  },
  {
    slug: 'salchichas-wudy',
    name: {
      en: 'Chicken and Turkey Sausages',
      es: 'Salchichas de pollo y pavo',
    },
    group: 'cooked-sausages',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'AIA Wudy',
    receipt: 'Salchichas de pollo y pavo AIA Wudy',
    price: 1.48,
    observedAt: '2026-08-14',
  },
  {
    slug: 'salchichon-pimienta',
    name: { en: 'Peppered Salchichón', es: 'Salchichón a la pimienta' },
    group: 'salchichon',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Sol',
    receipt: 'Salchichón a la pimienta SOL extra',
    price: 12.9,
    observedAt: '2026-08-21',
    perKilo: true,
  },
  {
    slug: 'snack-perro-biazoo',
    name: { en: 'Dog Chew Bones', es: 'Huesitos para perro' },
    group: 'dog-treats',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Biazoo',
    receipt: 'Snack perro duo huesitos BIAZOO',
    price: 0.82,
    observedAt: '2026-08-28',
  },
  {
    slug: 'snack-pincky',
    name: { en: 'Cream Filled Snack Cake', es: 'Bollo relleno de nata' },
    group: 'filled-buns',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Dulcesol',
    receipt: 'Snack pincky DULCESOL relleno nata',
    price: 0.99,
    observedAt: '2026-08-21',
  },
  {
    slug: 'snack-zebra',
    name: { en: 'Cocoa Filled Snack Cake', es: 'Bollo relleno de cacao' },
    group: 'filled-buns',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Dulcesol',
    receipt: 'Snack Zebra DULCESOL relleno de cacao',
    price: 0.99,
    observedAt: '2026-08-28',
  },
  {
    slug: 'tarta-whisky-dhul',
    name: { en: 'Whisky Cake Dessert', es: 'Tarta al whisky' },
    group: 'whisky-cake',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Dhul',
    receipt: 'Tarta al whisky DHUL 2x80 g',
    price: 1.89,
    observedAt: '2026-08-21',
  },
  {
    slug: 'tiras-bacon-elpozo',
    name: { en: 'Smoked Bacon Strips', es: 'Tiras de bacon ahumado' },
    group: 'bacon',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'ElPozo',
    receipt: 'Tiras de bacon ahumado ELPOZO Familiar',
    price: 1.45,
    observedAt: '2026-08-21',
  },
  {
    slug: 'tisana-susaron',
    name: { en: 'Horsetail Herbal Tea', es: 'Tisana de cola de caballo' },
    group: 'herbal-tea',
    category: PANTRY,
    defaultUnit: UNIT,
    brand: 'Susarón',
    receipt: 'Tisana SUSARÓN Adelgasana cola caballo',
    price: 1.39,
    observedAt: '2026-08-14',
  },
  {
    slug: 'tomate-entero-lata',
    name: { en: 'Whole Peeled Tomatoes', es: 'Tomate entero pelado' },
    group: 'tinned-tomatoes',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Tomate entero ALTEZA pelado lata 780',
    price: 1.36,
    observedAt: '2026-08-21',
  },
  {
    slug: 'tomate-frito-brik',
    name: { en: 'Fried Tomato Sauce', es: 'Tomate frito' },
    group: 'fried-tomato-sauce',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Alteza',
    receipt: 'Tomate frito ALTEZA brik 350 g',
    price: 0.49,
    observedAt: '2026-08-21',
  },
  {
    slug: 'yatekomo-yakisoba',
    name: {
      en: 'Instant Yakisoba Noodles',
      es: 'Fideos yakisoba instantáneos',
    },
    group: 'instant-noodles',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Gallina Blanca',
    receipt: 'Yatekomo Yakisoba classic GALLINA BLANCA',
    price: 1.52,
    observedAt: '2026-08-21',
  },
  {
    slug: 'yogur-liquido-nestle',
    name: {
      en: 'Pineapple and Coconut Drinking Yogurt',
      es: 'Yogur líquido de piña y coco',
    },
    group: 'drinking-yogurt',
    category: DAIRY,
    defaultUnit: LITER,
    brand: 'Nestlé',
    receipt: 'Yogur líquido NESTLÉ piña-coco 900',
    price: 1.16,
    observedAt: '2026-08-21',
  },
];
