import { ItemCategory, UnitOfMeasure } from '@portfolio/luna-shopper/contracts';
import type { AuthoredItem } from './types';

const { KILOGRAM, LITER, UNIT } = UnitOfMeasure;
const {
  BAKERY,
  BEVERAGES,
  DAIRY,
  FROZEN,
  HOUSEHOLD,
  MEAT,
  OTHER,
  PANTRY,
  PERSONAL_CARE,
  PRODUCE,
  SEAFOOD,
  SNACKS,
} = ItemCategory;

/**
 * The Mercadona half of the reference catalog: 116 products, one per distinct
 * line on the four Córdoba receipts, minus the two anchovy grades that are one
 * product bought twice (plan 0067, section 3).
 *
 * These are **authored products with receipt prices**, exactly like El Jamón's
 * and SuperCash's, and the 109 that carry an `ean` are additionally joined to
 * the harvest. That dual nature is the point, because the two databases this has
 * to work in are very different:
 *
 * - **A fresh database, which is most of them.** No discovery has run and none
 *   is going to: a catalog run is 4,383 requests over eighteen minutes, which is
 *   not a thing to do to populate a dev instance. So the seed creates all 117
 *   here, with these names and these prices, and that is the entire Mercadona
 *   catalog such a database has. It is small on purpose — the products actually
 *   bought, not an assortment.
 * - **A database that holds a harvest.** The 4,196 products are already there
 *   with fresher official prices. Creating these again would be 109 duplicate
 *   products, so the seed looks the EAN up, finds the harvested row, and sets
 *   only its `productGroupId`. The official price stands: it is newer than an
 *   August receipt, and `supermarket_items` holds one row per item per scope, so
 *   writing over it would destroy the better number rather than add to it.
 *
 * The eight without an `ean` are the ones no harvest carries at all, so there is
 * no barcode to write down. Five are a variant the snapshot holds under another
 * flavour; `CABALLA ESTORNINO` is the other kind, a fish counter product the
 * website has no row for because a website does not sell a fish counter.
 *
 * How the 109 were matched, since the file cannot show it: each till
 * abbreviation was scored against all 4,196 harvested names by token overlap,
 * and the receipt's own price had to agree before a match was accepted. 100 of
 * 109 agree to the cent; the nine that do not are weighed products, where the
 * receipt's figure is per kilogram and the catalog's is per fish, and they agree
 * against the per kilogram figure instead.
 */
export const MERCADONA_ITEMS: AuthoredItem[] = [
  // --- Produce and the fish counter ----------------------------------------
  {
    slug: 'banana',
    name: { en: 'Bananas', es: 'Plátanos' },
    group: 'bananas',
    category: PRODUCE,
    defaultUnit: KILOGRAM,
    receipt: 'BANANA',
    price: 1.5,
    observedAt: '2026-08-27',
    perKilo: true,
    ean: '2105433038243',
  },
  {
    slug: 'berenjena',
    name: { en: 'Aubergine', es: 'Berenjena' },
    group: 'aubergines',
    category: PRODUCE,
    defaultUnit: KILOGRAM,
    receipt: 'BERENJENA',
    price: 2.2,
    observedAt: '2026-08-27',
    perKilo: true,
    ean: '2105499693264',
  },
  {
    slug: 'parrillada-verduras',
    name: { en: 'Grilled Vegetable Mix', es: 'Parrillada de verduras' },
    group: 'grilled-vegetables',
    category: PRODUCE,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PARRILLADA VERDURA A',
    price: 1.65,
    observedAt: '2026-08-13',
    ean: '8480000610348',
  },
  // One product behind both grades the counter sells; the receipt's two prices
  // are what tell them apart and the catalog has one row for both.
  {
    slug: 'boqueron',
    name: { en: 'Fresh Anchovies', es: 'Boquerones frescos' },
    group: 'fresh-anchovies',
    category: SEAFOOD,
    defaultUnit: KILOGRAM,
    receipt: 'BOQUERÓN MED 51/80',
    alsoReceipt: ['BOQUERÓN PEQ 81/120'],
    price: 4.95,
    observedAt: '2026-08-27',
    perKilo: true,
    ean: '2105300816615',
  },
  {
    slug: 'trucha-arco-iris',
    name: { en: 'Rainbow Trout', es: 'Trucha arco iris' },
    group: 'rainbow-trout',
    category: SEAFOOD,
    defaultUnit: KILOGRAM,
    receipt: 'TRUCHA ARCO IRIS',
    price: 7.95,
    observedAt: '2026-08-27',
    perKilo: true,
    ean: '2105361812007',
  },
  {
    slug: 'dorada',
    name: { en: 'Sea Bream', es: 'Dorada' },
    group: 'sea-bream',
    category: SEAFOOD,
    defaultUnit: KILOGRAM,
    receipt: 'DORADA',
    price: 9.5,
    observedAt: '2026-05-21',
    perKilo: true,
    ean: '2105318812340',
  },
  {
    slug: 'corvina',
    name: { en: 'Meagre', es: 'Corvina' },
    group: 'meagre',
    category: SEAFOOD,
    defaultUnit: KILOGRAM,
    receipt: 'CORVINA',
    price: 9.2,
    observedAt: '2026-08-27',
    perKilo: true,
    ean: '2105300810552',
  },
  {
    slug: 'caballa-estornino',
    name: { en: 'Fresh Mackerel', es: 'Caballa estornino' },
    group: 'mackerel',
    category: SEAFOOD,
    defaultUnit: KILOGRAM,
    receipt: 'CABALLA ESTORNINO',
    price: 3.95,
    observedAt: '2026-08-27',
    perKilo: true,
  },
  {
    slug: 'palitos-surimi',
    name: { en: 'Surimi Sticks', es: 'Palitos de surimi' },
    group: 'surimi-sticks',
    category: FROZEN,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PALITOS SURIMI',
    price: 2.5,
    observedAt: '2026-08-27',
    ean: '8410063089096',
  },
  {
    slug: 'sardinas-oliva',
    name: { en: 'Sardines in Olive Oil', es: 'Sardinas en aceite de oliva' },
    group: 'tinned-sardines',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'SARDINAS OLIVA BIPAC',
    price: 2.2,
    observedAt: '2026-08-13',
    ean: '8480000182258',
  },
  {
    slug: 'sardinillas-sal',
    name: {
      en: 'Reduced Salt Small Sardines',
      es: 'Sardinillas reducidas en sal',
    },
    group: 'tinned-small-sardines',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'SARDINILLA RE. SAL O',
    price: 2.15,
    observedAt: '2026-08-13',
    ean: '8480000182142',
  },
  {
    slug: 'sardinillas-tomate',
    name: { en: 'Small Sardines in Tomato', es: 'Sardinillas en tomate' },
    group: 'tinned-small-sardines',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'SARDINILLAS TOMATE',
    price: 1.75,
    observedAt: '2026-08-13',
    ean: '8480000182098',
  },

  // --- Meat and charcuterie -------------------------------------------------
  {
    slug: 'salch-frankfurt',
    name: { en: 'Frankfurter Sausages', es: 'Salchichas Frankfurt' },
    group: 'frankfurter-sausages',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PACK-4 SALCH.FRANKF',
    price: 1.8,
    observedAt: '2026-08-27',
    ean: '8480000531414',
  },
  {
    slug: 'salchichas-gourmet',
    name: { en: 'Gourmet Cooked Sausages', es: 'Salchichas cocidas gourmet' },
    group: 'cooked-sausages',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'SALCHICHAS GOURMET',
    price: 2.45,
    observedAt: '2026-08-27',
    ean: '8480000531438',
  },
  {
    slug: 'frankfurt-viena-pavo',
    name: { en: 'Turkey Vienna Sausages', es: 'Salchichas Viena de pavo' },
    group: 'vienna-sausages',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'FRANKFURT VIENA PAVO',
    price: 1.5,
    observedAt: '2026-08-27',
  },
  {
    slug: 'fuet-espetec',
    name: { en: 'Fuet', es: 'Fuet espetec' },
    group: 'fuet',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'FUET ESPETEC EXTRA',
    price: 2.5,
    observedAt: '2026-08-27',
    ean: '8480000551085',
  },
  {
    slug: 'salami-montanes',
    name: { en: 'Mountain Salami', es: 'Salami montañés' },
    group: 'salami',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'El Pozo',
    receipt: 'SALAMI MONTAÑES',
    price: 1.85,
    observedAt: '2026-08-27',
    ean: '8410843011866',
  },
  {
    slug: 'mini-taquitos-jamon',
    name: { en: 'Diced Ham', es: 'Mini taquitos de jamón' },
    group: 'diced-ham',
    category: MEAT,
    defaultUnit: KILOGRAM,
    brand: 'Incarlopsa',
    receipt: 'MINI TAQUITOS JAMON',
    price: 2.65,
    observedAt: '2026-08-27',
    ean: '8421384016210',
  },
  {
    slug: 'torreznillos',
    name: { en: 'Smoked Pork Crackling', es: 'Torreznillos ahumados' },
    group: 'pork-crackling',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'TORREZNILLOS',
    price: 1.4,
    observedAt: '2026-08-27',
    ean: '8402001052248',
  },
  {
    slug: 'torrezno-morro',
    name: { en: 'Pork Crackling', es: 'Torreznos' },
    group: 'pork-crackling',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'TORREZNO MORRO',
    price: 1.4,
    observedAt: '2026-08-27',
    ean: '8402001038785',
  },

  // --- Dairy and desserts ---------------------------------------------------
  {
    slug: 'leche-semi-sin-lactosa',
    name: {
      en: 'Lactose Free Semi Skimmed Milk',
      es: 'Leche semidesnatada sin lactosa',
    },
    group: 'lactose-free-milk',
    category: DAIRY,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'LECHE SEMI S/LACT',
    price: 0.94,
    observedAt: '2026-08-27',
    ean: '8480000104731',
  },
  {
    slug: 'griego-limon',
    name: { en: 'Lemon Greek Yogurt', es: 'Yogur griego de limón' },
    group: 'greek-yogurt',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'GRIEGO LIMÓN',
    price: 1.65,
    observedAt: '2026-08-27',
    ean: '8480000226518',
  },
  {
    slug: 'yogomix',
    name: {
      en: "Children's Yogurt with Cereal Toppings",
      es: 'Yogur infantil con toppings',
    },
    group: 'childrens-yogurt',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'YOGOMIX X6',
    price: 3.15,
    observedAt: '2026-08-27',
    ean: '8480000284969',
  },
  {
    slug: 'natilla-proteinas-vainilla',
    name: {
      en: 'Vanilla Protein Custard',
      es: 'Natillas proteicas de vainilla',
    },
    group: 'protein-dessert',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    receipt: '+PROT NATILLA VAINI',
    price: 1.75,
    observedAt: '2026-08-27',
    ean: '8480000223111',
  },
  {
    slug: 'panna-cotta',
    name: { en: 'Panna Cotta with Caramel', es: 'Panna cotta con caramelo' },
    group: 'panna-cotta',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PANNA COTTA',
    price: 1.2,
    observedAt: '2026-08-27',
    ean: '8480000681881',
  },
  {
    slug: 'mousse-chocolate',
    name: { en: 'Chocolate Mousse', es: 'Mousse de chocolate' },
    group: 'chocolate-mousse',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'MOUSSE CHOCO P-4',
    price: 1.2,
    observedAt: '2026-06-17',
    ean: '8480000683502',
  },
  {
    slug: 'flan-cafe',
    name: { en: 'Coffee Crème Caramel', es: 'Flan de café' },
    group: 'creme-caramel',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'FLAN DE CAFÉ',
    price: 2.0,
    observedAt: '2026-08-13',
    ean: '8480000676337',
  },
  {
    slug: 'lonchas-queso',
    name: { en: 'Sliced Processed Cheese', es: 'Queso en lonchas fundido' },
    group: 'sliced-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'LONCHAS DE QUESO',
    price: 2.35,
    observedAt: '2026-08-27',
    ean: '8480000511829',
  },
  {
    slug: 'queso-rallado-fundir',
    name: { en: 'Grated Melting Cheese', es: 'Queso rallado especial fundir' },
    group: 'grated-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'Q RALLADO FUNDIR',
    price: 1.9,
    observedAt: '2026-08-27',
    ean: '8480000236227',
  },
  {
    slug: 'queso-polvo-pasta',
    name: { en: 'Powdered Cheese for Pasta', es: 'Queso en polvo para pasta' },
    group: 'grated-cheese',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'QUESO RALLADO POLVO',
    price: 1.25,
    observedAt: '2026-08-27',
    ean: '8422241807378',
  },
  {
    slug: 'porcion-regular',
    name: { en: 'Cheese Portions', es: 'Queso en porciones' },
    group: 'cheese-portions',
    category: DAIRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PORCIÓN REGULAR',
    price: 1.95,
    observedAt: '2026-08-27',
    ean: '8480000524058',
  },

  // --- Bakery ---------------------------------------------------------------
  {
    slug: 'pan-blanco-familiar',
    name: {
      en: 'Sliced White Bread, Family Size',
      es: 'Pan de molde blanco familiar',
    },
    group: 'sliced-white-bread',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PAN BLANCO FAMILIAR',
    price: 1.15,
    observedAt: '2026-08-27',
    ean: '8480000838674',
  },
  {
    slug: 'pan-hot-dog',
    name: { en: 'Hot Dog Rolls', es: 'Pan de perrito' },
    group: 'hot-dog-rolls',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PAN HOT DOG',
    price: 0.9,
    observedAt: '2026-08-27',
    ean: '8480000823328',
  },
  {
    slug: 'mini-biscotes',
    name: { en: 'Mini Melba Toast', es: 'Mini biscotes de trigo' },
    group: 'melba-toast',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'MINI BISCOTTE NORMAL',
    price: 0.76,
    observedAt: '2026-08-27',
    ean: '5601560111882',
  },
  {
    slug: 'croissant-cacao',
    name: {
      en: 'Cocoa Cream Croissant',
      es: 'Croissant relleno de crema de cacao',
    },
    group: 'filled-croissants',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CROISSANT RELL CACAO',
    price: 1.95,
    observedAt: '2026-08-27',
    ean: '8402001018817',
  },
  {
    slug: 'berlina-azucar',
    name: { en: 'Filled Berlin Doughnut', es: 'Berlina rellena' },
    group: 'filled-buns',
    category: BAKERY,
    defaultUnit: KILOGRAM,
    receipt: 'BERLINA AZUCAR',
    price: 1.25,
    observedAt: '2026-06-17',
    ean: '8402001057786',
  },

  // --- Snacks and confectionery --------------------------------------------
  {
    slug: 'pipa-gigante',
    name: {
      en: 'Giant Salted Sunflower Seeds',
      es: 'Pipas gigantes al agua y sal',
    },
    group: 'sunflower-seeds',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PIPA GIGANTE AGUASAL',
    price: 1.1,
    observedAt: '2026-08-27',
    ean: '8480000340788',
  },
  {
    slug: 'pistacho-tostado',
    name: { en: 'Roasted Pistachios', es: 'Pistachos tostados' },
    group: 'pistachios',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PISTACHO TOSTADO SAL',
    price: 3.4,
    observedAt: '2026-08-13',
    ean: '8480000861900',
  },
  {
    slug: 'cacahuete-chocolate',
    name: {
      en: 'Chocolate Coated Peanuts',
      es: 'Cacahuetes con chocolate con leche',
    },
    group: 'chocolate-coated-peanuts',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CACAHUETE CHOCOLATE',
    price: 2.05,
    observedAt: '2026-08-27',
    ean: '8480000123473',
  },
  {
    slug: 'cocktail-twist-up',
    name: {
      en: 'Lime and Pepper Nut Mix',
      es: 'Cóctel de frutos secos lima y pimienta',
    },
    group: 'nut-mix',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'COCKTAIL TWIST UP',
    price: 1.0,
    observedAt: '2026-08-13',
    ean: '8402001055416',
  },
  {
    slug: 'sticks-patata',
    name: { en: 'Potato Sticks', es: 'Sticks de patata' },
    group: 'potato-sticks',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'STICKS DE PATATA',
    price: 0.8,
    observedAt: '2026-06-17',
    ean: '8480000225689',
  },
  {
    slug: 'garfitos-queso',
    name: { en: 'Cheese Corn Puffs', es: 'Garfitos de maíz sabor queso' },
    group: 'corn-snacks',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'GARFITOS SABOR QUESO',
    price: 0.75,
    observedAt: '2026-08-27',
    ean: '8480000138897',
  },
  {
    slug: 'palomitas-mantequilla',
    name: {
      en: 'Butter Microwave Popcorn',
      es: 'Palomitas de mantequilla para microondas',
    },
    group: 'popcorn',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PALOMIT. MANTEQUILLA',
    price: 1.2,
    observedAt: '2026-06-17',
    ean: '8480000342126',
  },
  {
    slug: 'cuquis',
    name: { en: 'Savoury Biscuits', es: 'Galletas saladas Cuquis' },
    group: 'savoury-biscuits',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CUQUIS',
    price: 0.75,
    observedAt: '2026-06-17',
    ean: '8480000335814',
  },
  {
    slug: 'choco-blanco',
    name: { en: 'White Chocolate', es: 'Chocolate blanco' },
    group: 'white-chocolate',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CHOCO BLANCO',
    price: 1.1,
    observedAt: '2026-08-27',
    ean: '8480000124760',
  },
  {
    slug: 'choco-swing',
    name: { en: 'Swing Chocolate Bar', es: 'Chocolate Swing' },
    group: 'milk-chocolate',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CHOCO SWING',
    price: 3.95,
    observedAt: '2026-05-21',
  },
  {
    slug: 'fussion-roditas',
    name: {
      en: 'Biscuit Cream Filled White Chocolate',
      es: 'Chocolate blanco relleno de crema de galleta',
    },
    group: 'filled-chocolate',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'FUSSION RODITAS',
    price: 1.35,
    observedAt: '2026-08-13',
    ean: '8402001026263',
  },
  {
    slug: 'fussion-avellana',
    name: {
      en: 'Hazelnut Filled Chocolate',
      es: 'Chocolate Fussion de avellana',
    },
    group: 'filled-chocolate',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'FUSSION AVELLANA',
    price: 1.75,
    observedAt: '2026-06-17',
  },
  {
    slug: 'caramelo-nata',
    name: { en: 'Sugar Free Cream Sweets', es: 'Caramelos de nata sin azúcar' },
    group: 'boiled-sweets',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CARAMELO NATA S/AZUC',
    price: 1.15,
    observedAt: '2026-08-13',
    ean: '3215690801906',
  },
  {
    slug: 'aceituna-anchoa',
    name: { en: 'Anchovy Stuffed Olives', es: 'Aceitunas rellenas de anchoa' },
    group: 'olives',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'ACEITUNA R/ANCHOA P3',
    price: 3.0,
    observedAt: '2026-08-13',
    ean: '8402001001314',
  },
  {
    slug: 'mermelada-melocoton',
    name: { en: 'Peach Jam', es: 'Mermelada de melocotón' },
    group: 'jam',
    category: SNACKS,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'MERM. MELOCOTÓN',
    price: 1.35,
    observedAt: '2026-05-21',
    ean: '8480000866844',
  },

  // --- Frozen ---------------------------------------------------------------
  {
    slug: 'cono-nata',
    name: {
      en: 'Chocolate and Cream Ice Cream Cone',
      es: 'Cono de helado de choco nata',
    },
    group: 'ice-cream-cones',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'CONO NATA',
    price: 2.2,
    observedAt: '2026-08-13',
    ean: '8480000642516',
  },
  {
    slug: 'crocan-choc-vainilla',
    name: {
      en: 'Vanilla Crocan Ice Cream Cone',
      es: 'Cono de helado crocan de vainilla',
    },
    group: 'ice-cream-cones',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'CROCAN CHOC VAINILLA',
    price: 3.0,
    observedAt: '2026-06-17',
    ean: '8480000642301',
  },
  {
    slug: 'helado-turron',
    name: { en: 'Nougat Ice Cream', es: 'Helado de turrón' },
    group: 'ice-cream-tub',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'TURRÓN',
    price: 2.95,
    observedAt: '2026-08-13',
    ean: '8480000644459',
  },
  {
    slug: 'helado-golden-pecan',
    name: { en: 'Golden Pecan Ice Cream', es: 'Helado golden pecan' },
    group: 'ice-cream-tub',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'GOLDEN PECAN',
    price: 3.25,
    observedAt: '2026-05-21',
    ean: '8402001047299',
  },
  {
    slug: 'bombon-pistacho',
    name: {
      en: 'Pistachio Ice Cream Bars',
      es: 'Bombones helados de pistacho',
    },
    group: 'ice-cream-bars',
    category: FROZEN,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'BOMBÓN PISTACHO',
    price: 4.6,
    observedAt: '2026-06-17',
    ean: '8402001045264',
  },
  {
    slug: 'pizza-jamon',
    name: { en: 'Thin Crust Ham Pizza', es: 'Pizza de jamón masa fina' },
    group: 'frozen-pizza',
    category: FROZEN,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PIZZA JAMON M.FINA',
    price: 2.5,
    observedAt: '2026-06-17',
    ean: '8480000633392',
  },
  {
    slug: 'pizza-bbq',
    name: { en: 'Thin Crust Barbecue Pizza', es: 'Pizza barbacoa masa fina' },
    group: 'frozen-pizza',
    category: FROZEN,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PIZZA BBQ M.FINA',
    price: 2.5,
    observedAt: '2026-06-17',
    ean: '8480000226495',
  },
  {
    slug: 'pizza-atun',
    name: { en: 'Tuna Pizza', es: 'Pizza de atún' },
    group: 'frozen-pizza',
    category: FROZEN,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PIZZA DE ATUN',
    price: 2.6,
    observedAt: '2026-06-17',
    ean: '8480000635013',
  },

  // --- Pantry ---------------------------------------------------------------
  {
    slug: 'mayonesa',
    name: { en: 'Mayonnaise', es: 'Mayonesa' },
    group: 'mayonnaise',
    category: PANTRY,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'MAYONESA 500ML',
    price: 1.2,
    observedAt: '2026-06-17',
    ean: '8402001043550',
  },
  {
    slug: 'tomate-frito',
    name: { en: 'Fried Tomato Sauce', es: 'Tomate frito' },
    group: 'fried-tomato-sauce',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'TOMATE FRITO BRICK',
    price: 1.35,
    observedAt: '2026-08-27',
    ean: '8480000171320',
  },
  {
    slug: 'pimenton-dulce',
    name: { en: 'Sweet Paprika', es: 'Pimentón dulce' },
    group: 'paprika',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'PIMENTÓN DULCE LATA',
    price: 1.3,
    observedAt: '2026-05-21',
    ean: '8402001018756',
  },
  {
    slug: 'muesli-frutas',
    name: {
      en: 'Fruit and Nut Muesli',
      es: 'Muesli con frutas y frutos secos',
    },
    group: 'muesli',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'MUESLI CON FRUTAS',
    price: 2.1,
    observedAt: '2026-05-21',
    ean: '8480000094926',
  },
  {
    slug: 'capsula-extraforte',
    name: {
      en: 'Extra Strong Coffee Capsules',
      es: 'Cápsulas de café extra forte',
    },
    group: 'coffee-capsules',
    category: PANTRY,
    defaultUnit: UNIT,
    brand: 'Hacendado',
    receipt: 'CÁP. EXTRAFORTE',
    price: 3.45,
    observedAt: '2026-05-21',
    ean: '8402001049651',
  },
  {
    slug: 'cappuccino-caramelo',
    name: {
      en: 'Caramel Instant Cappuccino',
      es: 'Cappuccino soluble de caramelo',
    },
    group: 'instant-cappuccino',
    category: PANTRY,
    defaultUnit: KILOGRAM,
    brand: 'Hacendado',
    receipt: 'CAPPUCCINO CARAMELO',
    price: 2.75,
    observedAt: '2026-08-13',
    ean: '8480000676603',
  },
  {
    slug: 'cafe-leche-cappuccino',
    name: { en: 'Iced Cappuccino', es: 'Café con leche cappuccino' },
    group: 'iced-coffee',
    category: PANTRY,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'CAFÉ LECHE CAPPUCCIN',
    price: 0.75,
    observedAt: '2026-06-17',
    ean: '8402001038372',
  },

  // --- Drinks ---------------------------------------------------------------
  {
    slug: 'agua-mineral-grande',
    name: { en: 'Still Water, Large', es: 'Agua mineral grande' },
    group: 'still-water',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Solán de Cabras',
    receipt: 'AGUA MINERAL',
    price: 0.85,
    observedAt: '2026-08-27',
    ean: '8411547001085',
  },
  {
    slug: 'agua-mineral-pequena',
    name: { en: 'Still Water, Small', es: 'Agua mineral pequeña' },
    group: 'still-water',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Fuente Dehesa',
    receipt: 'F. DEHESA 500ML',
    price: 0.29,
    observedAt: '2026-05-21',
    ean: '7613287415691',
  },
  {
    slug: 'cerveza-clasica-lata',
    name: { en: 'Lager, Cans', es: 'Cerveza clásica en lata' },
    group: 'lager',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Steinburg',
    receipt: 'CERVEZA CLASICA LATA',
    price: 3.6,
    observedAt: '2026-08-13',
    ean: '8480000664624',
  },
  {
    slug: 'cerveza-clasica-pet',
    name: { en: 'Lager, Bottles', es: 'Cerveza clásica en botella' },
    group: 'lager',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Steinburg',
    receipt: 'CERVEZA CLASICA PET',
    price: 5.4,
    observedAt: '2026-08-13',
  },
  {
    slug: 'radler-sin-alcohol',
    name: { en: 'Alcohol Free Radler', es: 'Radler sin alcohol' },
    group: 'alcohol-free-radler',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Falke',
    receipt: "RADLER 0'0 PACK 8",
    price: 3.6,
    observedAt: '2026-05-21',
    ean: '8411090310559',
  },
  {
    slug: 'vino-blanco-brick',
    name: { en: 'White Wine', es: 'Vino blanco' },
    group: 'white-wine',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Casón Histórico',
    receipt: 'VINO BLANCO BRICK',
    price: 0.95,
    observedAt: '2026-08-13',
    ean: '8480000661272',
  },
  {
    slug: 'fruta-leche-pina-coco',
    name: {
      en: 'Pineapple and Coconut Fruit Milk Drink',
      es: 'Fruta + leche de piña y coco',
    },
    group: 'fruit-and-milk-drink',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'F. LECHE PIÑA COCO',
    price: 1.25,
    observedAt: '2026-08-13',
    ean: '8402001028847',
  },
  {
    slug: 'fruta-leche-tropical',
    name: { en: 'Tropical Fruit Milk Drink', es: 'Fruta + leche tropical' },
    group: 'fruit-and-milk-drink',
    category: BEVERAGES,
    defaultUnit: LITER,
    brand: 'Hacendado',
    receipt: 'F.LECHE TROPICAL',
    price: 0.95,
    observedAt: '2026-08-13',
    ean: '8402001024887',
  },

  // --- Household ------------------------------------------------------------
  {
    slug: 'friegasuelos-floral',
    name: { en: 'Floral Floor Cleaner', es: 'Friegasuelos floral' },
    group: 'floor-cleaner',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'FRIEGASUELOS FLORAL',
    price: 0.95,
    observedAt: '2026-05-21',
    ean: '8402001020926',
  },
  {
    slug: 'friegasuelos-tropical',
    name: { en: 'Tropical Floor Cleaner', es: 'Friegasuelos tropical' },
    group: 'floor-cleaner',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'FRIEGASUELO TROPICAL',
    price: 0.95,
    observedAt: '2026-08-13',
  },
  {
    slug: 'friegasuelos-insecticida',
    name: { en: 'Insecticide Floor Cleaner', es: 'Friegasuelos insecticida' },
    group: 'insecticide-floor-cleaner',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'FRIEG.INSECTICIDA',
    price: 2.35,
    observedAt: '2026-08-13',
    ean: '8402001060007',
  },
  {
    slug: 'lejia-detergente-limon',
    name: {
      en: 'Lemon Bleach with Detergent',
      es: 'Lejía con detergente de limón',
    },
    group: 'bleach',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'LEJIA DETERG.LIMON',
    price: 1.15,
    observedAt: '2026-08-27',
    ean: '8480000430540',
  },
  {
    slug: 'gel-wc-perfumado',
    name: { en: 'Toilet Cleaner Gel', es: 'Limpiador WC en gel' },
    group: 'toilet-cleaner',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'GEL WC PERFUMADO',
    price: 1.15,
    observedAt: '2026-05-21',
    ean: '8402001041402',
  },
  {
    slug: 'colgador-wc-glow',
    name: { en: 'Toilet Rim Block, Glow', es: 'Colgador WC Glow' },
    group: 'toilet-rim-block',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'COLGADOR WC GLOW',
    price: 1.3,
    observedAt: '2026-08-13',
    ean: '8402001050879',
  },
  {
    slug: 'colgador-wc-dalia',
    name: { en: 'Toilet Rim Block, Dahlia', es: 'Colgador WC dalia' },
    group: 'toilet-rim-block',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'COLGADOR WC DALIA',
    price: 1.3,
    observedAt: '2026-06-17',
  },
  {
    slug: 'limpiamuebles-cera',
    name: { en: 'Furniture Polish with Wax', es: 'Limpiamuebles con ceras' },
    group: 'furniture-polish',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'LIMPIAMUEBLES C/CERA',
    price: 1.65,
    observedAt: '2026-06-17',
    ean: '8402001007736',
  },
  {
    slug: 'disuelvemanchas',
    name: { en: 'Stain Dissolver', es: 'Disuelve manchas' },
    group: 'stain-remover',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'DISUELVEMANCHAS',
    price: 2.0,
    observedAt: '2026-05-21',
    ean: '8480000401786',
  },
  {
    slug: 'suavizante-hipoalergenico',
    name: {
      en: 'Hypoallergenic Fabric Softener',
      es: 'Suavizante hipoalergénico',
    },
    group: 'fabric-softener',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'SUAVI-HIPOALERGÉNICO',
    price: 1.8,
    observedAt: '2026-08-27',
    ean: '8402001027529',
  },
  {
    slug: 'eliminador-olores',
    name: {
      en: 'Fabric Odour Eliminator',
      es: 'Eliminador de olores para tejidos',
    },
    group: 'odour-eliminator',
    category: HOUSEHOLD,
    defaultUnit: LITER,
    brand: 'Bosque Verde',
    receipt: 'ELIMINADOR OLORES',
    price: 2.0,
    observedAt: '2026-06-17',
    ean: '8480000405524',
  },
  {
    slug: 'bolsas-basura-extra',
    name: {
      en: 'Extra Strong Bin Bags, 30 L',
      es: 'Bolsas de basura extra 30 L',
    },
    group: 'bin-bags',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: '30 B.BASURA EXTRA',
    price: 2.4,
    observedAt: '2026-05-21',
    ean: '8402001032844',
  },
  {
    slug: 'bolsas-basura-jardin',
    name: {
      en: 'Garden Bin Bags, 100 L',
      es: 'Bolsas de basura de jardín 100 L',
    },
    group: 'bin-bags',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: '10 S.JARDÍN C. FÁCIL',
    price: 2.85,
    observedAt: '2026-08-13',
    ean: '8480000497031',
  },
  {
    slug: 'bolsas-basura-compost',
    name: {
      en: 'Compostable Bin Bags, 10 L',
      es: 'Bolsas de basura compostables 10 L',
    },
    group: 'compostable-bin-bags',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: '20 B. BASURA COMPOST',
    price: 2.3,
    observedAt: '2026-05-21',
    ean: '8402001032875',
  },
  {
    slug: 'bayeta-cristales',
    name: {
      en: 'Glass Microfibre Cloth',
      es: 'Bayeta de microfibra para cristales',
    },
    group: 'cleaning-cloths',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'BAYETA MICROFIBRA CR',
    price: 0.85,
    observedAt: '2026-08-13',
    ean: '8480000228253',
  },
  {
    slug: 'bayetas-pequenas',
    name: {
      en: 'Small Microfibre Cloths',
      es: 'Bayetas pequeñas de microfibra',
    },
    group: 'cleaning-cloths',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'LOTE 3 BAYETAS PEQ.',
    price: 1.5,
    observedAt: '2026-05-21',
    ean: '8480000227744',
  },
  {
    slug: 'cubo-fregar-ruedas',
    name: { en: 'Mop Bucket with Wheels', es: 'Cubo de fregar con ruedas' },
    group: 'mop-bucket',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'CUBO FREGAR C/RUEDAS',
    price: 3.7,
    observedAt: '2026-05-21',
    ean: '8402001011672',
  },
  {
    slug: 'papel-higienico-suave',
    name: { en: 'Soft Toilet Paper', es: 'Papel higiénico suave' },
    group: 'toilet-paper',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'PAPEL HIGIÉNICO 4 CA',
    price: 3.7,
    observedAt: '2026-08-27',
    ean: '8402001032837',
  },
  {
    slug: 'rollo-hogar-doble',
    name: { en: 'Kitchen Roll', es: 'Papel de cocina' },
    group: 'kitchen-roll',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'ROLLO HOGAR DOBLE',
    price: 2.25,
    observedAt: '2026-08-13',
    ean: '8480000496195',
  },
  {
    slug: 'servilleta-2-capas',
    name: { en: 'Two Ply Paper Napkins', es: 'Servilletas de dos capas' },
    group: 'paper-napkins',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'SERVILLETA 2 CAPAS',
    price: 1.65,
    observedAt: '2026-08-13',
    ean: '8480000495891',
  },
  {
    slug: 'papel-vegetal',
    name: { en: 'Baking Paper', es: 'Papel vegetal' },
    group: 'baking-paper',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'PAPEL VEGETAL 30H',
    price: 1.7,
    observedAt: '2026-05-21',
    ean: '8480000236081',
  },
  {
    slug: 'papel-aluminio',
    name: { en: 'Aluminium Foil', es: 'Papel de aluminio' },
    group: 'aluminium-foil',
    category: HOUSEHOLD,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'PAPEL ALUMINIO',
    price: 2.3,
    observedAt: '2026-05-21',
  },

  // --- Personal care --------------------------------------------------------
  {
    slug: 'champu-argan',
    name: { en: 'Argan Oil Shampoo', es: 'Champú de aceite de argán' },
    group: 'shampoo',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Deliplus',
    receipt: 'CHAMPU ARGAN OIL',
    price: 1.9,
    observedAt: '2026-08-27',
    ean: '8480000443373',
  },
  {
    slug: 'recarga-jabon-manos',
    name: { en: 'Hand Soap Refill', es: 'Recarga de jabón de manos' },
    group: 'hand-soap',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Deliplus',
    receipt: 'REFILL DERMO',
    price: 1.4,
    observedAt: '2026-06-17',
    ean: '8480000229052',
  },
  {
    slug: 'deo-axe-dark',
    name: {
      en: 'Dark Temptation Deodorant',
      es: 'Desodorante Dark Temptation',
    },
    group: 'deodorant',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Axe',
    receipt: 'DEO AXE DARK TEMPT.',
    price: 3.3,
    observedAt: '2026-08-13',
    ean: '8720181072130',
  },
  {
    slug: 'deo-roll-on-avena',
    name: { en: 'Oat Roll On Deodorant', es: 'Desodorante roll-on de avena' },
    group: 'deodorant',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Deliplus',
    receipt: 'DEO ROLL-ON AVENA',
    price: 0.9,
    observedAt: '2026-08-13',
    ean: '8402001015656',
  },
  {
    slug: 'edp-rebel',
    name: {
      en: "Men's Eau de Parfum, Rebel",
      es: 'Eau de parfum de hombre, Rebel',
    },
    group: 'eau-de-parfum',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Como Tú',
    receipt: 'EDP REBEL',
    price: 8.0,
    observedAt: '2026-05-21',
    ean: '8402001009341',
  },
  {
    slug: 'spray-antiseptico',
    name: {
      en: 'Antiseptic Disinfectant Spray',
      es: 'Spray desinfectante antiséptico',
    },
    group: 'antiseptic-spray',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Deliplus',
    receipt: 'SPRAY ANTI SEPTIC',
    price: 1.8,
    observedAt: '2026-06-17',
    ean: '8480000794383',
  },
  {
    slug: 'discos-desmaquillantes',
    name: { en: 'Cotton Pads', es: 'Discos desmaquillantes' },
    group: 'cotton-pads',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'DISCOS DESM REDONDO',
    price: 1.0,
    observedAt: '2026-06-17',
    ean: '8480000794079',
  },
  {
    slug: 'protegeslip-cotton-maxi',
    name: { en: 'Cotton Maxi Panty Liners', es: 'Protegeslips cotton maxi' },
    group: 'panty-liners',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'PROTEG. COTTON MAXI',
    price: 1.9,
    observedAt: '2026-08-27',
    ean: '8480000473509',
  },
  {
    slug: 'protegeslip-dry-maxi',
    name: { en: 'Dry Maxi Panty Liners', es: 'Protegeslips dry maxi' },
    group: 'panty-liners',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'PROT. DRY MAXI',
    price: 2.5,
    observedAt: '2026-05-21',
    ean: '8480000473523',
  },
  {
    slug: 'toallitas-bebe',
    name: { en: 'Baby Wipes', es: 'Toallitas de bebé' },
    group: 'baby-wipes',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'TOALL.BEBE FRESC.80',
    price: 0.95,
    observedAt: '2026-08-13',
    ean: '8402001026027',
  },
  {
    slug: 'papel-humedo-wc',
    name: { en: 'Moist Toilet Tissue', es: 'Papel higiénico húmedo' },
    group: 'moist-toilet-tissue',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Bosque Verde',
    receipt: 'PAPEL HUMEDO WC',
    price: 1.55,
    observedAt: '2026-08-27',
    ean: '8480000472915',
  },
  {
    slug: 'quitaesmalte-acetona',
    name: {
      en: 'Nail Polish Remover with Acetone',
      es: 'Quitaesmalte con acetona',
    },
    group: 'nail-polish-remover',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Deliplus',
    receipt: 'QUITAESMALTE C/ACET',
    price: 1.15,
    observedAt: '2026-08-13',
    ean: '8480000796318',
  },
  {
    slug: 'laca-gel-brillo',
    name: { en: 'Gloss Gel Top Coat', es: 'Top coat de gel brillo' },
    group: 'nail-top-coat',
    category: PERSONAL_CARE,
    defaultUnit: LITER,
    brand: 'Deliplus',
    receipt: 'LACA GEL BRILLO',
    price: 3.5,
    observedAt: '2026-08-27',
    ean: '8480000422866',
  },
  {
    slug: 'mascara-long-xtrem',
    name: { en: 'Long Xtrem Mascara', es: 'Máscara de pestañas Long Xtrem' },
    group: 'mascara',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'MÁSCARA LONG XTREM',
    price: 4.5,
    observedAt: '2026-06-17',
    ean: '8402001040665',
  },
  {
    slug: 'blush-mate',
    name: { en: 'Matte Blusher', es: 'Colorete mate' },
    group: 'blusher',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'BLUSH MATE 3',
    price: 5.0,
    observedAt: '2026-06-17',
    ean: '8480000803955',
  },
  {
    slug: 'perfilador-labios',
    name: { en: 'Lip Liner', es: 'Perfilador de labios' },
    group: 'lip-liner',
    category: PERSONAL_CARE,
    defaultUnit: UNIT,
    brand: 'Deliplus',
    receipt: 'PERF.LABIOS 06',
    price: 2.5,
    observedAt: '2026-06-17',
    ean: '8480000223500',
  },

  // --- Pet ------------------------------------------------------------------
  {
    slug: 'comida-perro-compy',
    name: {
      en: 'Dry Dog Food with Beef and Chicken',
      es: 'Pienso para perro de ternera y pollo',
    },
    group: 'dry-dog-food',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Compy',
    receipt: 'C.TERNERA/POLLO/VERD',
    price: 16.5,
    observedAt: '2026-08-27',
    ean: '8402001030642',
  },
  {
    slug: 'salchicha-perro',
    name: { en: 'Dog Sausage Treats', es: 'Salchichas para perro' },
    group: 'dog-treats',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Delikuit',
    receipt: 'SALCH.POLLO Y ARROZ',
    price: 1.8,
    observedAt: '2026-06-17',
    ean: '8480000520968',
  },
  {
    slug: 'arena-gatos',
    name: {
      en: 'Antibacterial Cat Litter',
      es: 'Arena para gato antibacterias',
    },
    group: 'cat-litter',
    category: OTHER,
    defaultUnit: KILOGRAM,
    brand: 'Nuske',
    receipt: 'ARENA DE GATOS',
    price: 1.5,
    observedAt: '2026-08-13',
    ean: '8412239000973',
  },
  {
    slug: 'bolsas-doggybag',
    name: { en: 'Dog Waste Bags', es: 'Bolsas para excrementos de perro' },
    group: 'dog-waste-bags',
    category: OTHER,
    defaultUnit: UNIT,
    brand: 'Nuske',
    receipt: '45 BOLSAS DOGGYBAG',
    price: 1.3,
    observedAt: '2026-06-17',
    ean: '5060079620580',
  },
];
