import {
  ToothTreatment,
  ToothTreatmentStatus,
  ToothZones,
  TreatmentType,
} from '@portfolio/odontogram/models';
import { WithRequired } from '@portfolio/shared/util';

export const TOOTH_TREATMENTS: readonly WithRequired<ToothTreatment, 'id'>[] = [
  {
    id: '1',
    odontogram: '1',
    teeth: ['11', '12', '21'],
    groupTeeth: true,
    status: ToothTreatmentStatus.COMPLETED,
    zones: [ToothZones.ROOT],
    type: TreatmentType.EXTRACTION,
    additionalInformation: 'Extraction treatment for teeth 11, 12, and 21',
    updatedAt: new Date('2025-01-02'),
    createdAt: new Date('2025-01-01'),
  },
  {
    id: '2',
    odontogram: '1',
    teeth: ['37'],
    groupTeeth: true,
    status: ToothTreatmentStatus.PENDING,
    zones: [ToothZones.BOTTOM, ToothZones.RIGHT],
    type: TreatmentType.STANDARD,
    additionalInformation: 'Standard treatment for teeth 37',
    updatedAt: new Date('2025-02-02'),
    createdAt: new Date('2025-02-01'),
  },
  {
    id: '3',
    odontogram: '2',
    teeth: ['11', '12', '21'],
    groupTeeth: false,
    status: ToothTreatmentStatus.PENDING,
    zones: [ToothZones.ROOT],
    type: TreatmentType.IMPLANT,
    additionalInformation: 'Implant treatment for teeth 11, 12, and 21',
    updatedAt: new Date('2025-03-02'),
    createdAt: new Date('2025-03-01'),
  },
  {
    id: '4',
    odontogram: '3',
    teeth: ['28'],
    groupTeeth: false,
    status: ToothTreatmentStatus.COMPLETED,
    zones: [ToothZones.LATERAL],
    type: TreatmentType.STANDARD,
    additionalInformation: 'Filling for tooth 28',
    updatedAt: new Date('2025-04-02'),
    createdAt: new Date('2025-04-01'),
  },
  {
    id: '5',
    odontogram: '3',
    teeth: ['27'],
    groupTeeth: false,
    status: ToothTreatmentStatus.COMPLETED,
    zones: [ToothZones.LATERAL],
    type: TreatmentType.STANDARD,
    additionalInformation: 'Filling for tooth 27',
    updatedAt: new Date('2025-04-02'),
    createdAt: new Date('2025-04-01'),
  },
  {
    id: '6',
    odontogram: '3',
    teeth: ['37'],
    groupTeeth: false,
    status: ToothTreatmentStatus.COMPLETED,
    zones: [ToothZones.LATERAL],
    type: TreatmentType.STANDARD,
    additionalInformation: 'Filling for tooth 37',
    updatedAt: new Date('2025-04-02'),
    createdAt: new Date('2025-04-01'),
  },
  {
    id: '7',
    odontogram: '3',
    teeth: ['44'],
    groupTeeth: false,
    status: ToothTreatmentStatus.COMPLETED,
    zones: [ToothZones.TOP, ToothZones.BOTTOM],
    type: TreatmentType.STANDARD,
    additionalInformation: 'Filling for tooth 44',
    updatedAt: new Date('2025-04-02'),
    createdAt: new Date('2025-04-01'),
  },
  {
    id: '8',
    odontogram: '3',
    teeth: ['44'],
    groupTeeth: false,
    status: ToothTreatmentStatus.PENDING,
    zones: [ToothZones.RIGHT, ToothZones.LEFT, ToothZones.CENTER],
    type: TreatmentType.STANDARD,
    additionalInformation: 'Filling for tooth 44',
    updatedAt: new Date('2025-04-02'),
    createdAt: new Date('2025-04-01'),
  },
];
